import { join } from 'node:path';
import { buildWorld } from '@maritime/world';
import { createDb, runMigrations, withTx } from '@maritime/service-kit';
import { env } from './env';
import { createStorage, newStorageKey, type Storage } from './storage';
import { resolveMime } from './mime';
import { sha256Of } from './documents.service';

/** A one-page PDF with a line of text — valid enough for every viewer, small enough to seed by the hundred. */
export function minimalPdf(text: string): Buffer {
  const escaped = text.replace(/[\\()]/g, (c) => `\\${c}`).replace(/[^\x20-\x7e]/g, '?');
  const content = `BT /F1 12 Tf 48 790 Td (${escaped}) Tj ET`;
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 595 842] /Contents 4 0 R /Resources << /Font << /F1 5 0 R >> >> >>',
    `<< /Length ${Buffer.byteLength(content)} >>\nstream\n${content}\nendstream`,
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
  ];
  let body = '%PDF-1.4\n'; const offsets: number[] = [];
  objects.forEach((o, i) => { offsets.push(Buffer.byteLength(body)); body += `${i + 1} 0 obj\n${o}\nendobj\n`; });
  const xref = Buffer.byteLength(body);
  body += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n${offsets.map((o) => `${String(o).padStart(10, '0')} 00000 n \n`).join('')}trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xref}\n%%EOF\n`;
  return Buffer.from(body, 'latin1');
}
/** An empty zip archive (end-of-central-directory record only). */
export const EMPTY_ZIP = Buffer.from([0x50, 0x4b, 0x05, 0x06, ...new Array<number>(18).fill(0)]);

/** Seeds the incident case files and the latest service-request lodgements from the shared world: fictional names, generated bytes, real hashes. Idempotent: skipped once any document exists. */
export async function seedDocuments(databaseUrl: string, profile?: string, storage?: Storage) {
  const store = storage ?? createStorage(env());
  const { pool } = createDb(databaseUrl);
  await runMigrations(pool, join(__dirname, '..', 'migrations'));
  const world = buildWorld({ profile });
  const existing = await pool.query<{ n: string }>('SELECT count(*) AS n FROM documents');
  if (Number(existing.rows[0].n) > 0) { await pool.end(); return { documents: 0, profile: world.profile, skipped: true }; }
  const userId = new Map(world.users.map((u) => [u.name, u.id]));
  interface Item { entityType: string; entityId: string; name: string; docType: string; uploadedBy: { id: string; name: string }; at: string; note: string; audiencePerm: string }
  const items: Item[] = [];
  for (const inc of world.incidents) for (const d of inc.documents) items.push({ entityType: 'Incident', entityId: inc.id, name: d.name, docType: d.docType, uploadedBy: { id: userId.get(d.uploadedBy) ?? 'seed', name: d.uploadedBy }, at: d.at, note: d.note, audiencePerm: 'incidents.view' });
  for (const req of world.serviceRequests.slice(-60)) for (const d of req.documents) items.push({ entityType: 'ServiceRequest', entityId: req.id, name: d.fileName, docType: 'SUPPORTING', uploadedBy: { id: req.applicant.userId ?? 'applicant', name: req.applicant.name }, at: d.uploadedAt, note: d.notes, audiencePerm: 'services.view' });
  const prepared: Array<{ it: Item; mime: string; body: Buffer; key: string }> = [];
  for (const it of items) {
    const mime = resolveMime(undefined, it.name); if (!mime) continue;
    const body = mime === 'application/pdf' ? minimalPdf(`${it.name} - ${it.entityType} ${it.entityId} (sample)`) : mime === 'application/zip' ? EMPTY_ZIP : Buffer.from(`${it.name} (sample)\n`, 'utf8');
    const key = newStorageKey(); await store.put(key, body, mime);
    prepared.push({ it, mime, body, key });
  }
  const n = await withTx(pool, async (c) => {
    for (const p of prepared) {
      const r = await c.query<{ id: string }>(
        `INSERT INTO documents(entity_type, entity_id, name, doc_type, mime, size_bytes, sha256, storage_key, uploaded_by, audience_perm, virus_status, note, created_at, updated_at)
         VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,'SKIPPED',$11,$12,$12) RETURNING id`,
        [p.it.entityType, p.it.entityId, p.it.name, p.it.docType, p.mime, p.body.length, sha256Of(p.body), p.key, JSON.stringify(p.it.uploadedBy), p.it.audiencePerm, p.it.note, p.it.at]);
      await c.query('INSERT INTO document_versions(document_id, version, name, mime, size_bytes, sha256, storage_key, uploaded_by, note, created_at) VALUES ($1,1,$2,$3,$4,$5,$6,$7,$8,$9)', [r.rows[0].id, p.it.name, p.mime, p.body.length, sha256Of(p.body), p.key, JSON.stringify(p.it.uploadedBy), p.it.note, p.it.at]);
    }
    return prepared.length;
  });
  await pool.end();
  return { documents: n, profile: world.profile };
}
if (require.main === module) { const e = env(); seedDocuments(e.DATABASE_URL).then((c) => console.log('SEED COMPLETE', c)).catch((err) => { console.error(err); process.exit(1); }); }
