/* The two faces a model has: its entry in the platform's registry (governance) and its fits on the model server. */
export interface RegistryVersion { id: string; version: number; artifactRef: string; framework: string; trainingRunId: string | null; metrics: Record<string, unknown>; params: Record<string, unknown>; status: 'DRAFT' | 'VALIDATED' | 'APPROVED' | 'DEPLOYED' | 'RETIRED'; changeNote: string; createdBy: string | null; validatedBy: string | null; approvedBy: string | null; approvedAt: string | null; retiredAt: string | null; createdAt: string; updatedAt: string }
export interface RegistryDeployment { id: string; version: number; environment: 'DEV' | 'UAT' | 'PROD'; status: string; endpoint: string; replicas: number; residencyRegion: string; note: string; deployedBy: string | null; deployedAt: string; retiredAt: string | null }
export interface RegistryRun { id: string; datasetRef: string; datasetRows: number; params: Record<string, unknown>; metrics: Record<string, unknown>; status: string; note: string; initiatedBy: string | null; startedAt: string; finishedAt: string | null }
export interface RegistryModel {
  id: string; key: string; name: string; nameAr: string | null; task: string; purpose: string; purposeAr: string | null; owner: string; framework: string;
  residency: { region: string; note: string }; status: 'ACTIVE' | 'RETIRED'; currentVersion: number | null; serving: Partial<Record<'DEV' | 'UAT' | 'PROD', number>>;
}
export interface RegistryModelDetail extends RegistryModel { versions: RegistryVersion[]; deployments: RegistryDeployment[]; trainingRuns: RegistryRun[]; baselines: { version: number; sampleSize: number }[] }

export interface FitMetrics { rows?: number; trained?: number; heldOut?: number; auc?: number; precision?: number; recall?: number; f1?: number; logLoss?: number; accuracy?: number; positiveRate?: number; precisionAtBaseRate?: number; lift?: number; mae?: number; rmse?: number; r2?: number; baselineMae?: number; labelStd?: number; confidence?: number; importance?: Record<string, number>; featureSet?: string }
export interface Artefact { id: string; model: string; version: number; task: string; artifactRef: string; framework: string; featureSet: string | null; features: string[]; schema: { name: string; kind: 'num' | 'cat'; median?: number; categories?: string[] }[]; metrics: FitMetrics; trees: number; depth: number; learningRate: number; trainingRunId: string | null; createdAt: string }
export interface FitRun { id: string; model: string; datasetId: string | null; params: Record<string, unknown>; metrics: FitMetrics; status: 'RUNNING' | 'SUCCEEDED' | 'FAILED'; error: string | null; initiatedBy: string; version: number | null; registryVersion: number | null; registryRunId: string | null; startedAt: string; finishedAt: string | null; durationMs: number | null }
export interface FitDefaults { rounds: number; depth: number; learningRate: number; minLeaf: number; holdout: number; seed: number; patience?: number }
export interface ServerModel {
  key: string; task: 'CLASSIFICATION' | 'REGRESSION'; name: string; description: string; label: string; unit: string | null;
  features: { name: string; kind: 'num' | 'cat'; description: string }[]; featureSets: { name: string; features: string[]; note: string }[];
  artefacts: Artefact[]; latest: Artefact | null; lastRun: FitRun | null; runs: number; served: { calls: number; p50Ms: number | null; p95Ms: number | null; lastAt: string | null }; defaults: FitDefaults;
}
export interface ServerModelDetail extends Omit<ServerModel, 'runs'> { runs: FitRun[]; datasets: { id: string; builtAt: string; rows: number; positives: number | null; labelMean: number | null; labelStd: number | null; note: string }[]; minRows: number }
export interface DatasetPreview { model: string; featureSet: string; features: string[]; rows: number; positives: number | null; labelMean: number; labelStd: number; schema: Artefact['schema']; sample: { features: Record<string, unknown>; label: number }[]; builtAt: string; label: string; unit: string | null }
export interface TrainOutcome { run: FitRun; artefact: Artefact; dataset: { rows: number; positives: number | null; featureSet: string }; registry: { ok: true; version: number; status: string; trainingRunId: string; created: boolean } | { ok: false; error: string; httpStatus?: number } | null }
export interface ServingStats { windowDays: number; budgetMs: number; mode: string; servers: { modelServer: string; endpoint: string | null; fallback: string }; calls: number; breaches: number; withinSlaPct: number; latencyMs: { p50: number; p95: number; p99: number; max: number }; models: { model: string; calls: number; failures: number; breaches: number; withinSlaPct: number; latencyMs: { p50: number; p95: number; p99: number; max: number } }[] }
