/** The licensing engine is subject-agnostic: one lifecycle, numbering, audit trail and public verification for every regulated instrument. */
export const SUBJECT_KINDS = ['COMPANY', 'VESSEL', 'SEAFARER', 'PORT_FACILITY', 'MET_INSTITUTION'] as const;
export type SubjectKind = (typeof SUBJECT_KINDS)[number];
export const INSTRUMENT_CLASSES = ['LICENCE', 'PERMIT', 'CERTIFICATE', 'ACCREDITATION', 'ENDORSEMENT', 'NOC'] as const;
export type InstrumentClass = (typeof INSTRUMENT_CLASSES)[number];

export const VESSEL_STATUTORY_CERT_TYPES = [
  'CARGO_SHIP_SAFETY_CONSTRUCTION', 'CARGO_SHIP_SAFETY_EQUIPMENT', 'CARGO_SHIP_SAFETY_RADIO',
  'INTERNATIONAL_LOAD_LINE', 'IOPP_CERTIFICATE', 'IAPP_CERTIFICATE', 'SEWAGE_POLLUTION_PREVENTION',
  'SAFETY_MANAGEMENT_CERTIFICATE', 'SHIP_SECURITY_CERTIFICATE', 'MARITIME_LABOUR_CERTIFICATE',
  'TONNAGE_CERTIFICATE', 'MINIMUM_SAFE_MANNING_DOCUMENT',
  // added by the rebuild from the RFP's Domain 1 list and the capability deck
  'CIVIL_LIABILITY_CERTIFICATE', 'CONTINUOUS_SYNOPSIS_RECORD', 'EXEMPTION_CERTIFICATE', 'CERTIFICATE_OF_OWNERSHIP',
  'BALLAST_WATER_MANAGEMENT', 'ANTI_FOULING_SYSTEM', 'BUNKER_LIABILITY_CERTIFICATE', 'WRECK_REMOVAL_LIABILITY',
] as const;
export const COMPANY_STATUTORY_CERT_TYPES = ['DOCUMENT_OF_COMPLIANCE'] as const;
export const ENDORSEMENT_KINDS = ['ANNUAL', 'INTERMEDIATE', 'RENEWAL', 'ADDITIONAL'] as const;
export const ENDORSEMENT_RESULTS = ['ENDORSED', 'ENDORSED_WITH_CONDITIONS', 'NOT_ENDORSED'] as const;

export const COMPANY_LICENSE_TYPES = ['SHIPPING_AGENCY', 'BUNKER_SUPPLIER', 'SHIP_CHANDLER', 'REPAIR_YARD',
  'MANNING_AGENCY', 'MARINE_SURVEYOR', 'TRAINING_INSTITUTE', 'PORT_FACILITY_ISPS', 'STEVEDORE', 'DIVING_CONTRACTOR',
  'SHIP_MANAGEMENT', 'MARINA_OR_JETTY', 'RECOGNISED_ORGANISATION',
  // the six specialised accreditation categories of RFP Domain 7
  'COMPASS_CALIBRATION', 'LSA_SERVICING', 'FFA_SERVICING', 'SMALL_VESSEL_SURVEY', 'PEST_CONTROL', 'TOWAGE_CERTIFICATION',
  ...COMPANY_STATUTORY_CERT_TYPES] as const;
export const VESSEL_LICENSE_TYPES = ['NAVIGATION_LICENCE', 'FOREIGN_VESSEL_PERMIT', 'VESSEL_NOC', ...VESSEL_STATUTORY_CERT_TYPES] as const;
export const SEAFARER_LICENSE_TYPES = ['CERTIFICATE_OF_COMPETENCY', 'CERTIFICATE_OF_PROFICIENCY', 'FLAG_STATE_ENDORSEMENT',
  'CERTIFICATE_OF_RECEIPT_OF_APPLICATION', 'SEAMAN_CARD', 'GMDSS_CERTIFICATE', 'MEDICAL_FITNESS_CERTIFICATE'] as const;
export const PORT_FACILITY_LICENSE_TYPES = ['ISPS_STATEMENT_OF_COMPLIANCE'] as const;
export const MET_LICENSE_TYPES = ['MET_INSTITUTION_ACCREDITATION', 'MET_PROGRAMME_APPROVAL'] as const;

export const LICENSE_TYPES_BY_SUBJECT: Record<SubjectKind, readonly string[]> = {
  COMPANY: COMPANY_LICENSE_TYPES,
  VESSEL: VESSEL_LICENSE_TYPES,
  SEAFARER: SEAFARER_LICENSE_TYPES,
  PORT_FACILITY: PORT_FACILITY_LICENSE_TYPES,
  MET_INSTITUTION: MET_LICENSE_TYPES,
};
export const LICENSE_TYPES: string[] = Object.values(LICENSE_TYPES_BY_SUBJECT).flat();

export const INSTRUMENT_CLASS_BY_TYPE: Record<string, InstrumentClass> = {
  NAVIGATION_LICENCE: 'LICENCE', FOREIGN_VESSEL_PERMIT: 'PERMIT', VESSEL_NOC: 'NOC',
  CERTIFICATE_OF_COMPETENCY: 'CERTIFICATE', CERTIFICATE_OF_PROFICIENCY: 'CERTIFICATE',
  FLAG_STATE_ENDORSEMENT: 'ENDORSEMENT', CERTIFICATE_OF_RECEIPT_OF_APPLICATION: 'CERTIFICATE',
  SEAMAN_CARD: 'CERTIFICATE', GMDSS_CERTIFICATE: 'CERTIFICATE', MEDICAL_FITNESS_CERTIFICATE: 'CERTIFICATE',
  ISPS_STATEMENT_OF_COMPLIANCE: 'CERTIFICATE',
  MET_INSTITUTION_ACCREDITATION: 'ACCREDITATION', MET_PROGRAMME_APPROVAL: 'ACCREDITATION',
  // the six RFP accreditation schemes run on an annual cycle, so they are accreditations rather than two-year licences
  COMPASS_CALIBRATION: 'ACCREDITATION', LSA_SERVICING: 'ACCREDITATION', FFA_SERVICING: 'ACCREDITATION', SMALL_VESSEL_SURVEY: 'ACCREDITATION', PEST_CONTROL: 'ACCREDITATION', TOWAGE_CERTIFICATION: 'ACCREDITATION',
  ...Object.fromEntries([...VESSEL_STATUTORY_CERT_TYPES, ...COMPANY_STATUTORY_CERT_TYPES].map((t) => [t, 'CERTIFICATE' as InstrumentClass])),
};
export const NUMBER_PREFIX_BY_CLASS: Record<InstrumentClass, string> = {
  LICENCE: 'LIC', PERMIT: 'PRM', CERTIFICATE: 'CRT', ACCREDITATION: 'ACC', ENDORSEMENT: 'END', NOC: 'NOC',
};
/** Each register numbers in its own series; type takes precedence over class. */
export const NUMBER_PREFIX_BY_TYPE: Record<string, string> = {
  NAVIGATION_LICENCE: 'NAV', CERTIFICATE_OF_COMPETENCY: 'COC', CERTIFICATE_OF_PROFICIENCY: 'COP',
  FLAG_STATE_ENDORSEMENT: 'FSE', CERTIFICATE_OF_RECEIPT_OF_APPLICATION: 'CRA', SEAMAN_CARD: 'SMC-ID',
  GMDSS_CERTIFICATE: 'GMDSS', MEDICAL_FITNESS_CERTIFICATE: 'MED',
  ISPS_STATEMENT_OF_COMPLIANCE: 'ISPS', MET_INSTITUTION_ACCREDITATION: 'MET', MET_PROGRAMME_APPROVAL: 'MPA',
  COMPASS_CALIBRATION: 'ACC-CMP', LSA_SERVICING: 'ACC-LSA', FFA_SERVICING: 'ACC-FFA', SMALL_VESSEL_SURVEY: 'ACC-SVS', PEST_CONTROL: 'ACC-PST', TOWAGE_CERTIFICATION: 'ACC-TOW',
  CARGO_SHIP_SAFETY_CONSTRUCTION: 'SAFCON', CARGO_SHIP_SAFETY_EQUIPMENT: 'SEQ', CARGO_SHIP_SAFETY_RADIO: 'SRC',
  INTERNATIONAL_LOAD_LINE: 'ILL', IOPP_CERTIFICATE: 'IOPP', IAPP_CERTIFICATE: 'IAPP', SEWAGE_POLLUTION_PREVENTION: 'ISPP',
  SAFETY_MANAGEMENT_CERTIFICATE: 'SMC', SHIP_SECURITY_CERTIFICATE: 'ISSC', MARITIME_LABOUR_CERTIFICATE: 'MLC',
  TONNAGE_CERTIFICATE: 'TON', MINIMUM_SAFE_MANNING_DOCUMENT: 'MSMD', DOCUMENT_OF_COMPLIANCE: 'DOC',
  CIVIL_LIABILITY_CERTIFICATE: 'CLC', CONTINUOUS_SYNOPSIS_RECORD: 'CSR', EXEMPTION_CERTIFICATE: 'EXM',
  CERTIFICATE_OF_OWNERSHIP: 'OWN', BALLAST_WATER_MANAGEMENT: 'BWM', ANTI_FOULING_SYSTEM: 'AFS',
  BUNKER_LIABILITY_CERTIFICATE: 'BCLC', WRECK_REMOVAL_LIABILITY: 'WRC',
};
/** Which permission group governs each subject kind. */
export const SUBJECT_PERMS: Record<SubjectKind, string> = {
  COMPANY: 'facilities', PORT_FACILITY: 'facilities', MET_INSTITUTION: 'facilities', VESSEL: 'vessels', SEAFARER: 'seafarers',
};
export const VALIDITY_MONTHS: Record<InstrumentClass, number> = { LICENCE: 24, PERMIT: 6, CERTIFICATE: 60, ACCREDITATION: 12, ENDORSEMENT: 60, NOC: 3 };
export const VALIDITY_MONTHS_BY_TYPE: Record<string, number> = { TONNAGE_CERTIFICATE: 1200, MINIMUM_SAFE_MANNING_DOCUMENT: 1200, CONTINUOUS_SYNOPSIS_RECORD: 1200 };

export const instrumentClassOf = (type: string): InstrumentClass => INSTRUMENT_CLASS_BY_TYPE[type] ?? 'LICENCE';
export const numberPrefixOf = (type: string): string => NUMBER_PREFIX_BY_TYPE[type] ?? NUMBER_PREFIX_BY_CLASS[instrumentClassOf(type)];
export const validityMonthsOf = (type: string): number => VALIDITY_MONTHS_BY_TYPE[type] ?? VALIDITY_MONTHS[instrumentClassOf(type)];
export const typeAllowedFor = (subjectKind: SubjectKind, type: string): boolean => LICENSE_TYPES_BY_SUBJECT[subjectKind]?.includes(type) ?? false;

/** The six accreditation schemes of RFP Domain 7, as the contract knows them; Data Studio's `accreditationCategory` master carries each one's cycle. */
export const ACCREDITATION_CATEGORY_TYPES = ['COMPASS_CALIBRATION', 'LSA_SERVICING', 'FFA_SERVICING', 'SMALL_VESSEL_SURVEY', 'PEST_CONTROL', 'TOWAGE_CERTIFICATION'] as const;
export const isAccreditationScheme = (type: string): boolean => (ACCREDITATION_CATEGORY_TYPES as readonly string[]).includes(type);
