export interface LookupCategory { key: string; label: string; labelAr?: string }
/** The nineteen reference-data categories of the Data Studio, plus the categories the rebuild adds. */
export const LOOKUP_CATEGORIES: LookupCategory[] = [
  { key: 'vesselType',     label: 'Vessel Types' },
  { key: 'cargoType',      label: 'Cargo Types' },
  { key: 'port',           label: 'Ports (UN/LOCODE)' },
  { key: 'agent',          label: 'Shipping Agents' },
  { key: 'deficiencyCode', label: 'Deficiency Codes' },
  { key: 'actionCode',     label: 'PSC Action Codes' },
  { key: 'country',        label: 'Countries' },
  { key: 'state',          label: 'States' },
  { key: 'city',           label: 'Cities' },
  { key: 'uom',            label: 'Units of Measure' },
  { key: 'currency',       label: 'Currencies' },
  { key: 'equipmentType',  label: 'Equipment Types' },
  { key: 'equipment',      label: 'Equipment & Assets' },
  { key: 'department',     label: 'Departments' },
  { key: 'designation',    label: 'Designations' },
  { key: 'shift',          label: 'Shifts' },
  { key: 'documentType',   label: 'Document Types' },
  { key: 'incidentArea',   label: 'Incident Locations' },
  { key: 'holiday',        label: 'Holiday Calendar' },
];

/** Per-module settings — defaults merged under the setting key `module:<key>`. */
export const MODULE_SETTING_DEFAULTS: Record<string, Record<string, unknown>> = {
  ops:       { vcnPrefix: 'REF', anchorageAlertHrs: 24, defaultTugsUnder250m: 2, defaultTugsOver250m: 3, scheduleWindowDays: 5, channelSpeedLimitKn: 8, aisGapAlertMin: 30, anchorDriftNm: 0.2, zoneEntryWatch: true },
  ships:     { certExpiringDays: 30, dryDockReminderDays: 60, riskRefreshMinutes: 30 },
  crew:      { medicalExpiringDays: 45, minRestHours: 10, cocVerifyOnSignOn: true },
  legis:     { ackRequiredDefault: false, ackReminderDays: 7, showSupersededDays: 365 },
  incidents: { mttaTargetMin: 30, mttrTargetHrs: 24, autoNotifySeverity: 'HIGH', reopenWindowDays: 30, injuryReportHrs: 24 },
  inspect:   { findingDueDays: 14, detentionThreshold: 1, passScorePct: 80, requireEvidencePhotos: false },
  facil:     { licenceValidityYears: 2, auditIntervalMonths: 12, renewalReminderDays: 90 },
  finance:   { invoicePrefix: 'REF/INV', paymentTermsDays: 30, overdueReminderDays: 7, roundTotalsToWholeUnit: true },
  mis:       { defaultPeriodMonths: 12, exportFooter: 'Generated by the Maritime Platform' },
  masters:   { allowHardDelete: false },
  agents:    { defaultAutonomy: 'SUPERVISED', escalationHours: 4, suspensionNoticeHours: 4 },
  admin:     { sessionTimeoutMin: 60, passwordMinLength: 8, auditRetentionDays: 1825, mfaRequiredForStaff: true },
};

export const SETTING_SECTIONS = ['org', 'operations', 'billing', 'notifications', 'smtp', 'ai', 'riskWeights'] as const;
export const CERT_EXPIRING_DAYS = 30;
export const SEAFARER_RANKS = ['Master', 'Chief Officer', 'Second Officer', 'Third Officer', 'Chief Engineer',
  'Second Engineer', 'Third Engineer', 'Fourth Engineer', 'Electro-Technical Officer', 'Bosun', 'Able Seaman',
  'Ordinary Seaman', 'Oiler', 'Fitter', 'Cook', 'Steward', 'Deck Cadet', 'Engine Cadet'] as const;
export const SEAFARER_CERT_TYPES = ['Certificate of Competency', 'GMDSS GOC', 'Medical Fitness (ILO/MLC)',
  'STCW Basic Safety Training', 'Advanced Fire Fighting', 'Medical First Aid', 'Ship Security Officer',
  'Tanker Familiarisation', 'Certificate of Discharge (CDC)'] as const;
export const RESOURCE_TYPES = ['TUG', 'PILOT_LAUNCH', 'MOORING_BOAT', 'PILOT', 'SURVEY_LAUNCH'] as const;
export const DEFAULT_RISK_WEIGHTS = { age: 15, certificates: 25, deficiencies: 20, detentions: 20, inspectionGap: 10, agentPerformance: 10 };
export const NOTIFICATION_SEVERITIES = ['info', 'success', 'warning', 'error'] as const;
export type NotificationSeverity = (typeof NOTIFICATION_SEVERITIES)[number];

/** Tenancy scopes carried on identities and records. */
export const SCOPE_LEVELS = ['NATIONAL', 'PORT', 'ZONE', 'FACILITY', 'COMPANY'] as const;
export type ScopeLevel = (typeof SCOPE_LEVELS)[number];
export interface TenancyScope { level: ScopeLevel; ports?: string[]; zones?: string[]; facilities?: string[]; companies?: string[] }
export const NATIONAL_SCOPE: TenancyScope = { level: 'NATIONAL' };
