import { getJurisdiction, INCIDENT_CATEGORIES, INCIDENT_TYPES, INCIDENT_STATUS, INCIDENT_SEVERITY, INCIDENT_PRIORITIES, INCIDENT_SOURCES } from '@maritime/contracts';
import { Prng, D, H, HIST_START, stableId, iso, yearOf, makeSeries } from './prng';
import { hist, type WorldHistoryEntry } from './common';
import { usersByRole, userNamed, type WorldUser } from './people';
import type { WorldBerth } from './organisations';
import type { WorldPortCall } from './operations';
import type { WorldVessel } from './vessels';
import { geoFor } from './geo';

export type IncidentCategory = (typeof INCIDENT_CATEGORIES)[number]; export type IncidentType = (typeof INCIDENT_TYPES)[number]; export type IncidentStatus = (typeof INCIDENT_STATUS)[number];
export type IncidentSeverity = (typeof INCIDENT_SEVERITY)[number]; export type IncidentPriority = (typeof INCIDENT_PRIORITIES)[number]; export type IncidentSource = (typeof INCIDENT_SOURCES)[number];
export interface WorldIncidentComm { at: string; by: string; channel: IncidentSource; direction: 'IN' | 'OUT' | 'INTERNAL'; message: string }
export interface WorldIncidentDoc { name: string; docType: string; sizeKB: number; uploadedBy: string; at: string; note: string }
export interface WorldIncidentTask { title: string; assigneeId: string | null; assignee: string; due: string; status: 'OPEN' | 'DONE'; doneAt: string | null }
export interface WorldIncident {
  id: string; number: string; category: IncidentCategory; type: IncidentType; severity: IncidentSeverity; priority: IncidentPriority; status: IncidentStatus; title: string; description: string;
  vesselId: string | null; vesselName: string; berthId: string | null; berthCode: string; location: { area: string; lat: number; lon: number }; reportedAt: string; reportedBy: string; source: IncidentSource;
  assignedToId: string; assignedTo: string; assets: string[]; injuries: number; pollutionTier: number; weather: { windKn: number; seaState: number }; comms: WorldIncidentComm[]; documents: WorldIncidentDoc[]; tasks: WorldIncidentTask[];
  log: { at: string; by: string; entry: string }[]; statusHistory: WorldHistoryEntry[]; rca: { rootCause: string; category: string; correctiveAction: string; preventiveAction: string }; acknowledgedAt: string | null; resolvedAt: string | null; closedAt: string | null; outcome: string;
}
type Helpers = { p: <T>(a: readonly T[]) => T; n: (a: number, b: number) => number; berth: string; vessel: string };
type Tpl = { cat: IncidentCategory; type: IncidentType; sev: IncidentSeverity[]; w: number; tier?: number; berth?: boolean; vessel?: boolean; injuries?: number; title: (x: Helpers) => string };
const TEMPLATES: Tpl[] = [
  { cat: 'ENVIRONMENT', type: 'OIL_SPILL', sev: ['MEDIUM', 'MEDIUM', 'HIGH'], w: 8, tier: 1, berth: true, title: (x) => `Oil sheen observed at ${x.berth} during ${x.p(['bunkering', 'hose disconnection', 'ballast operations', 'sludge transfer'])}` },
  { cat: 'ENVIRONMENT', type: 'POLLUTION', sev: ['LOW', 'MEDIUM'], w: 6, berth: true, title: (x) => `${x.p(['Floating debris', 'Garbage overflow from a skip', 'Dust plume beyond the sprinkler line', 'Grey-water discharge observed'])} near ${x.berth}` },
  { cat: 'PERSONNEL', type: 'PERSONNEL_INJURY', sev: ['MEDIUM', 'MEDIUM', 'HIGH'], w: 12, injuries: 1, berth: true, title: (x) => `Stevedore ${x.p(['hand injury during lashing', 'ankle injury on the quay apron', 'fall from a container stack ladder', 'struck by a swinging sling load'])} at ${x.berth}` },
  { cat: 'PERSONNEL', type: 'MEDICAL_EVAC', sev: ['HIGH'], w: 5, vessel: true, title: (x) => `Medical evacuation — crew member with ${x.p(['chest pain', 'suspected appendicitis', 'severe dehydration', 'crush injury to the hand'])} on ${x.vessel}` },
  { cat: 'MARINE', type: 'MOORING_FAILURE', sev: ['MEDIUM', 'HIGH'], w: 7, berth: true, vessel: true, title: (x) => `Mooring line parted during ${x.p(['a squall', 'spring tide', 'passing-vessel surge'])} — ${x.vessel} at ${x.berth}` },
  { cat: 'MARINE', type: 'COLLISION', sev: ['HIGH', 'CRITICAL'], w: 3, berth: true, vessel: true, title: (x) => `Heavy contact with the fender while berthing — ${x.vessel} at ${x.berth}` },
  { cat: 'MARINE', type: 'NEAR_MISS', sev: ['LOW', 'LOW', 'MEDIUM'], w: 11, berth: true, title: (x) => `Near miss — ${x.p(['pilot ladder step gave way', 'crane hook swung over the gangway', 'tug line slipped off the bitt', 'forklift reversed towards the gang', 'container twist-lock found unsecured'])} at ${x.berth}` },
  { cat: 'MARINE', type: 'SAR', sev: ['HIGH', 'CRITICAL'], w: 4, title: (x) => `Fishing boat ${x.p(['adrift with engine failure', 'taking water', 'with a fouled propeller', 'reported overdue'])} ${x.n(3, 9)} nm ${x.p(['SW', 'SE', 'S'])} of the fairway buoy` },
  { cat: 'SECURITY', type: 'SECURITY_BREACH', sev: ['LOW', 'MEDIUM'], w: 7, title: (x) => `${x.p(['Unauthorised drone sighting', 'Tailgating attempt', 'Unidentified small craft in the security zone', 'Dock pass reported lost', 'Perimeter fence damage found'])} — ${x.p(['CT-4 yard', 'Gate 3', 'West Basin approach', 'ISPS Zone B', 'Gate 1 truck lane'])}` },
  { cat: 'EQUIPMENT', type: 'EQUIPMENT_FAILURE', sev: ['LOW', 'MEDIUM', 'MEDIUM', 'HIGH'], w: 13, berth: true, title: (x) => `${x.p(['STS crane boom-limit fault', 'Shore gangway hydraulic failure', 'Quay crane gearbox over-temperature', 'Mooring winch brake slip', 'Conveyor belt tear on the bulk stream', 'Harbour mobile crane outrigger alarm'])} at ${x.berth}` },
  { cat: 'CARGO', type: 'CARGO_DAMAGE', sev: ['LOW', 'MEDIUM'], w: 9, berth: true, title: (x) => `${x.p(['Container dropped during lashing', 'Torn fertiliser bags on the stack', 'Wet-damaged steel coils found', 'Reefer power interruption on the yard', 'Project cargo shifted on the trailer'])} at ${x.berth}` },
  { cat: 'NAVIGATION', type: 'NAV_HAZARD', sev: ['MEDIUM'], w: 4, title: (x) => x.p(['Drifting container reported in the approach channel', 'Unlit fishing-net marker in the channel', 'Channel buoy No. 7 light reported unlit', 'Dredger pipeline marker adrift']) },
  { cat: 'HSE', type: 'FIRE', sev: ['HIGH', 'CRITICAL'], w: 4, berth: true, title: (x) => `${x.p(['Small fire in the conveyor gallery', 'Engine-room fire alarm', 'Hot-work spark ignition on the lashing bridge', 'Transformer room smoke detected'])} — ${x.berth}` },
  { cat: 'MARINE', type: 'GROUNDING', sev: ['CRITICAL'], w: 1, title: (x) => `Bunker barge touched bottom near ${x.p(['the western shallows', 'channel edge marker 7'])} — refloated on the rising tide` },
];
const SEV_HOURS: Record<IncidentSeverity, [number, number]> = { LOW: [4, 30], MEDIUM: [8, 72], HIGH: [4, 48], CRITICAL: [3, 24] };
const PRIORITY: Record<IncidentSeverity, IncidentPriority> = { LOW: 'P4', MEDIUM: 'P3', HIGH: 'P2', CRITICAL: 'P1' };
const RCA: [string, string, string, string][] = [
  ['Mooring line worn beyond discard criteria', 'Equipment', 'Line renewed from ship\'s stores; full mooring inspection done', 'Quarterly mooring-line audit added to the berth checklist'],
  ['SOP not followed during hose disconnection', 'Procedure', 'Operation stopped; hose crew re-briefed and drip trays repositioned', 'Hose-handling refresher training for all jetty crews'],
  ['Hydraulic hose fatigue on the crane boom circuit', 'Equipment', 'Hose replaced; adjacent circuits pressure-tested', 'Hose replacement interval halved in the PM plan'],
  ['Inadequate lighting at the work site', 'Human factor', 'Portable mast lighting positioned; work rescheduled to day shift', 'Lux survey of all cargo work areas each quarter'],
  ['Sudden squall — weather within forecast limits', 'Weather', 'Additional lines run; tug held on standby until wind eased', 'Mooring standard raised for cape vessels in the windy season'],
  ['Third-party craft error in the fairway', 'External', 'Craft escorted clear; owner advised through the fisheries association', 'Joint awareness drive with the fishing harbour association'],
  ['Lashing gear failure under dynamic load', 'Equipment', 'Damaged units quarantined; batch inspection completed', 'Supplier batch certificates now verified at the gate'],
];
const DOCS: [string, string][] = [['first-information-report.pdf', 'REPORT'], ['site-photographs.zip', 'PHOTO'], ['masters-statement.pdf', 'STATEMENT'], ['water-sample-analysis.pdf', 'SAMPLE'], ['cctv-clip-gate3.mp4', 'CCTV'], ['crane-maintenance-log.pdf', 'REPORT'],
  ['boom-deployment-photos.zip', 'PHOTO'], ['injury-medical-report.pdf', 'REPORT'], ['permit-to-work-scan.pdf', 'PERMIT'], ['damage-survey-report.pdf', 'REPORT'], ['toolbox-talk-record.pdf', 'REPORT'], ['line-failure-analysis.pdf', 'REPORT']];
const TASKS = ['Deploy containment boom', 'Collect water samples for analysis', 'Obtain master\'s statement via agent', 'Arrange ambulance and first aid', 'Isolate equipment and tag out', 'Notify the environment authority', 'Notify the coast guard station',
  'Review CCTV footage of the period', 'Arrange diver inspection of hull/fender', 'File P&I / insurance notification', 'Conduct toolbox talk with the stevedore gang', 'Civil team to inspect fender and cope line', 'Restrict berth until survey clears'];

/** ~110 cases since 2023 held at a flat rate, plus the live desk. Cases involve the fictional fleet only — never a documented liner caller. */
export function buildIncidents(rng: Prng, profile: string, users: WorldUser[], vessels: WorldVessel[], berths: WorldBerth[], portCalls: WorldPortCall[], now: Date): WorldIncident[] {
  const ae = getJurisdiction(profile).code === 'AE'; const geo = geoFor(profile); const histDays = Math.floor((now.getTime() - HIST_START.getTime()) / D);
  const fleet = vessels.filter((v) => !v.real); const vByName = new Map(fleet.map((v) => [v.name, v])); const bByCode = new Map(berths.map((b) => [b.code, b])); const operational = berths.filter((b) => b.status === 'OPERATIONAL').map((b) => b.code);
  const hse = users.filter((u) => /HSE|Environment|Fire Station/.test(u.designation) && u.roleName === 'Marine Surveyor'); const duty = usersByRole(users, 'NMC Duty Officer').slice(0, 4); const marine = usersByRole(users, 'Harbour Master').slice(0, 4);
  const chiefHse = userNamed(users, /Chief — HSE/) ?? hse[0]; const envOfficer = userNamed(users, /Environment Officer/) ?? hse[0]; const dutyLead = duty[0]; const pfso = userNamed(users, /PFSO/) ?? duty[1] ?? dutyLead;
  const reporters = ['Jetty supervisor', 'Berth foreman', 'Terminal duty manager', 'Master via agent', 'VHF Ch 16 watch', 'ISPS patrol — Gate 3', 'Crane operator', 'Marine control room', 'Stevedore gang leader', 'Pilot on board', 'Tug master', ae ? 'Port police post — Gate 1' : 'CISF post — Gate 1'];
  const comms: [IncidentSource, WorldIncidentComm['direction'], string][] = [['VHF', 'IN', 'Master confirms situation under control; no assistance required at this time.'], ['VHF', 'IN', 'Tug master reports on scene; commencing assessment.'],
    ['VHF', 'OUT', 'Marine control to all stations: restrict small-craft movement near the affected berth until further notice.'], ['PHONE', 'OUT', 'Informed the coast guard station; reference number logged in the register.'],
    ['PHONE', 'OUT', `${ae ? 'Environment agency regional office' : 'Pollution control board regional office'} informed as a precaution; sampling arranged.`], ['PHONE', 'IN', 'Agent confirms P&I correspondent has been notified and surveyor is en route.'],
    ['EMAIL', 'OUT', 'Preliminary incident notification circulated to HM, HSE and terminal management.'], ['EMAIL', 'IN', 'Master\'s statement and crew list received from the agent.'], ['PORTAL', 'INTERNAL', 'First responders logged on scene; area cordoned as per SOP.'],
    ['PORTAL', 'INTERNAL', 'Boom deployed as a precaution; skimmer on standby.'], ['PORTAL', 'INTERNAL', 'Work resumed after toolbox talk and equipment inspection.'], ['PORTAL', 'INTERNAL', 'CCTV footage of the period secured for review.'],
    ['PHONE', 'IN', 'Port clinic confirms the injured person is stable.'], ['VHF', 'IN', 'Pilot reports vessel all fast; no further damage observed.'], ['EMAIL', 'OUT', 'Corrective action plan requested from the contractor within 48 hours.']];
  const fvNames = ae ? ['Al Shaheen', 'Dana', 'Al Marjan', 'Saqr'] : ['Jal Pari', 'Dariya Sathi', 'Matsya Kanya', 'Sagar Putra'];
  const pool = TEMPLATES.flatMap((t) => Array.from({ length: t.w }, () => t)); const out: WorldIncident[] = [];
  const times = Array.from({ length: 110 }, () => new Date(now.getTime() - Math.floor(rng.next() * (histDays - 4) + 3) * D - rng.int(0, 23) * H)).sort((a, b) => a.getTime() - b.getTime());
  for (const reportedAt of times) {
    const t = rng.pick(pool); const h: Helpers = { p: (a) => rng.pick(a), n: (a, b) => rng.int(a, b), berth: t.berth ? rng.pick(operational) : '', vessel: t.vessel ? rng.pick(fleet).name : '' };
    const severity = rng.pick(t.sev); const officer = rng.pick(['SECURITY', 'NAVIGATION', 'MARINE'].includes(t.cat) ? [...duty, ...marine] : hse); const ageD = (now.getTime() - reportedAt.getTime()) / D;
    // lifecycle by age: old cases are closed; the recent tail is a live pipeline
    const status: IncidentStatus = ageD > 30 ? (rng.chance(0.94) ? 'CLOSED' : 'RESOLVED') : ageD > 7 ? rng.pick(['CLOSED', 'CLOSED', 'CLOSED', 'RESOLVED', 'RESOLVED', 'MONITORING']) : rng.pick(['OPEN', 'ACKNOWLEDGED', 'RESPONDING', 'RESPONDING', 'MONITORING', 'RESOLVED']);
    const ackAt = new Date(reportedAt.getTime() + rng.int(4, 55) * 60000); const respAt = new Date(ackAt.getTime() + rng.int(10, 90) * 60000);
    const resolvedAt = new Date(respAt.getTime() + rng.int(SEV_HOURS[severity][0], SEV_HOURS[severity][1]) * H); const closedAt = new Date(resolvedAt.getTime() + rng.int(18, 90) * H);
    const reach = { OPEN: 0, ACKNOWLEDGED: 1, RESPONDING: 2, MONITORING: 2, RESOLVED: 3, CLOSED: 4 }[status]; const rca = rng.pick(RCA);
    const history = [hist('', 'OPEN', reportedAt, 'Marine control room', 'Incident logged')];
    if (reach >= 1) history.push(hist('OPEN', 'ACKNOWLEDGED', ackAt, officer.name)); if (reach >= 2) history.push(hist('ACKNOWLEDGED', 'RESPONDING', respAt, officer.name, 'Response initiated'));
    if (status === 'MONITORING') history.push(hist('RESPONDING', 'MONITORING', respAt.getTime() + rng.int(2, 10) * H, officer.name, 'Situation contained — monitoring'));
    if (reach >= 3) history.push(hist('RESPONDING', 'RESOLVED', resolvedAt, officer.name, rca[2])); if (reach >= 4) history.push(hist('RESOLVED', 'CLOSED', closedAt, chiefHse.name, 'RCA reviewed and case closed'));
    const log = [{ at: iso(reportedAt), by: 'Marine control room', entry: 'Incident logged in the portal; duty officer paged' }, ...history.slice(1).map((x) => ({ at: x.at, by: x.by, entry: `Status moved to ${x.to}${x.note ? ` — ${x.note}` : ''}` }))];
    const berth = h.berth ? bByCode.get(h.berth) : undefined; const vessel = h.vessel ? vByName.get(h.vessel) : undefined; const pos = berth ? geo.berthPos[berth.code] : undefined; const area = pos ? undefined : rng.pick(geo.areas);
    out.push({ id: '', number: '', category: t.cat, type: t.type, severity, priority: PRIORITY[severity], status, title: t.title(h), description: 'Logged from the first information report; see the communications thread and documents for the working record.',
      vesselId: vessel?.id ?? null, vesselName: vessel?.name ?? (t.type === 'SAR' ? `FV ${rng.pick(fvNames)} (FV-REG-${rng.int(1000, 1999)})` : ''), berthId: berth?.id ?? null, berthCode: berth?.code ?? '',
      location: { area: berth?.code ?? area![0], lat: pos ? pos[0] : area![1] + rng.int(-20, 20) / 1000, lon: pos ? pos[1] : area![2] + rng.int(-20, 20) / 1000 }, reportedAt: iso(reportedAt), reportedBy: rng.pick(reporters), source: rng.pick(['VHF', 'PHONE', 'PORTAL', 'PATROL', 'CCTV']),
      assignedToId: officer.id, assignedTo: officer.name, assets: t.type === 'SAR' ? ['Tug TUG-01', 'Pilot launch PLT-02'] : t.tier ? ['Boom crew A', 'Tug TUG-05 (spill kit)'] : [], injuries: t.injuries && rng.chance(0.9) ? t.injuries : 0, pollutionTier: t.tier && reach >= 2 ? t.tier : 0,
      weather: { windKn: rng.int(6, 26), seaState: rng.int(1, 5) },
      comms: Array.from({ length: rng.int(2, 6) }, (_, ci) => { const c = rng.pick(comms); return { at: iso(reportedAt.getTime() + (ci + 1) * rng.int(20, 200) * 60000), by: ci % 2 ? officer.name : rng.pick(reporters), channel: c[0], direction: c[1], message: c[2] }; }),
      documents: Array.from({ length: rng.int(0, 4) }, () => { const d = rng.pick(DOCS); return { name: d[0], docType: d[1], sizeKB: rng.int(80, 8200), uploadedBy: officer.name, at: iso(reportedAt.getTime() + rng.int(2, 40) * H), note: '' }; }),
      tasks: Array.from({ length: rng.int(0, 4) }, () => { const done = reach >= 3 || rng.chance(0.5); const due = reportedAt.getTime() + rng.int(1, 5) * D; const who = rng.pick([...hse, ...duty]); return { title: rng.pick(TASKS), assigneeId: who.id, assignee: who.name, due: iso(due), status: done ? 'DONE' as const : 'OPEN' as const, doneAt: done ? iso(due - rng.int(2, 20) * H) : null }; }),
      log, statusHistory: history, rca: reach >= 3 ? { rootCause: rca[0], category: rca[1], correctiveAction: rca[2], preventiveAction: rca[3] } : { rootCause: '', category: '', correctiveAction: '', preventiveAction: '' },
      acknowledgedAt: reach >= 1 ? iso(ackAt) : null, resolvedAt: reach >= 3 ? iso(resolvedAt) : null, closedAt: reach >= 4 ? iso(closedAt) : null, outcome: reach >= 3 ? rca[2] : '' });
  }
  // the live desk: eight marquee cases in the states a duty officer actually sees
  const ago = (hours: number) => new Date(now.getTime() - hours * H); const berthedNow = portCalls.filter((c) => c.status === 'BERTHED' && vByName.has(c.vesselName));
  const liquidCall = berthedNow.find((c) => c.berthCode?.startsWith('LB')) ?? berthedNow[0]; const lb2 = bByCode.get('LB-2'); const ct41 = bByCode.get('CT4-1');
  const live = (p: Partial<WorldIncident> & Pick<WorldIncident, 'category' | 'type' | 'severity' | 'status' | 'title' | 'description' | 'reportedAt' | 'source' | 'assignedToId' | 'assignedTo' | 'statusHistory'>): WorldIncident => ({
    id: '', number: '', priority: PRIORITY[p.severity], vesselId: null, vesselName: '', berthId: null, berthCode: '', location: { area: geo.areas[0][0], lat: geo.areas[0][1], lon: geo.areas[0][2] }, reportedBy: 'Marine control room', assets: [], injuries: 0, pollutionTier: 0,
    weather: { windKn: 12, seaState: 2 }, comms: [], documents: [], tasks: [], log: [{ at: p.reportedAt, by: 'Marine control room', entry: 'Incident logged; duty officer paged' }], rca: { rootCause: '', category: '', correctiveAction: '', preventiveAction: '' },
    acknowledgedAt: p.statusHistory.find((h) => h.to === 'ACKNOWLEDGED' || h.to === 'RESPONDING')?.at ?? null, resolvedAt: p.statusHistory.find((h) => h.to === 'RESOLVED')?.at ?? null, closedAt: p.statusHistory.find((h) => h.to === 'CLOSED')?.at ?? null, outcome: '', ...p });
  const task = (title: string, who: WorldUser, due: Date, done: Date | null): WorldIncidentTask => ({ title, assigneeId: who.id, assignee: who.name, due: iso(due), status: done ? 'DONE' : 'OPEN', doneAt: done ? iso(done) : null });
  const anch = geo.areas[1]; const fairway = geo.areas[2];
  out.push(live({ category: 'PERSONNEL', type: 'CASUALTY', severity: 'CRITICAL', status: 'RESOLVED', title: 'Crew member lost overboard from a bulk carrier at anchorage — recovered deceased',
    description: 'Able seaman missing at anchorage muster; recovered by the pilot launch 40 minutes later. CPR unsuccessful. Flag state and P&I correspondent informed the same day.', vesselName: ae ? 'MV Ras Ghanada Trader' : 'MV Anchor Roads Trader',
    location: { area: anch[0], lat: anch[1], lon: anch[2] }, reportedAt: iso(ago(96)), reportedBy: 'Vessel master via VHF Ch 16', source: 'VHF', assignedToId: dutyLead.id, assignedTo: dutyLead.name, assets: ['Pilot launch PLT-02'], injuries: 1, weather: { windKn: 14, seaState: 3 },
    comms: [{ at: iso(ago(95.4)), by: dutyLead.name, channel: 'VHF', direction: 'IN', message: 'Master reports one AB unaccounted for at muster; last seen on the forecastle.' }, { at: iso(ago(94.7)), by: dutyLead.name, channel: 'PHONE', direction: 'OUT', message: 'Casualty reported to the flag state duty desk and the P&I correspondent.' }, { at: iso(ago(93)), by: 'Pilot launch coxswain', channel: 'VHF', direction: 'IN', message: 'Person recovered from the water; CPR in progress on the launch.' }],
    documents: [{ name: 'master-statement.pdf', docType: 'STATEMENT', sizeKB: 310, uploadedBy: dutyLead.name, at: iso(ago(70)), note: 'Taken via the agent' }, { name: 'casualty-report-flagstate.pdf', docType: 'REPORT', sizeKB: 540, uploadedBy: dutyLead.name, at: iso(ago(30)), note: 'Submitted copy' }],
    tasks: [task('Notify flag state and P&I correspondent', dutyLead, ago(90), ago(94.7)), task('Collect witness statements from the anchor watch', dutyLead, ago(48), ago(52))],
    statusHistory: [hist('', 'OPEN', ago(96), 'Marine control room', 'Casualty reported'), hist('OPEN', 'RESPONDING', ago(95.6), dutyLead.name, 'Launch tasked to the anchorage'), hist('RESPONDING', 'RESOLVED', ago(46), dutyLead.name, 'Recovery complete; report submitted. Held open pending statutory closure.')],
    rca: { rootCause: 'Working alone on deck in darkness without a lifejacket or a lookout', category: 'Human factor', correctiveAction: 'Master\'s standing orders amended: no lone deck work at anchor between sunset and sunrise', preventiveAction: 'Anchorage safety circular issued to all agents; lifejacket compliance added to the boarding checklist' },
    outcome: 'Body recovered and repatriated; investigation report with the flag state. Case remains open for statutory closure.' }));
  out.push(live({ category: 'HSE', type: 'NEAR_MISS', severity: 'LOW', status: 'CLOSED', title: 'Forklift reversed toward a lashing gang at CT1 — no contact, work paused', description: 'Terminal operator\'s shift report by email: forklift reversed without a banksman while a lashing gang crossed the apron. No injury; toolbox talk held before work resumed.',
    berthId: bByCode.get('CT1-2')?.id ?? null, berthCode: 'CT1-2', location: { area: 'CT1 apron', lat: geo.berthPos['CT1-2'][0], lon: geo.berthPos['CT1-2'][1] }, reportedAt: iso(ago(60)), reportedBy: 'Terminal shift supervisor', source: 'EMAIL', assignedToId: envOfficer.id, assignedTo: envOfficer.name, weather: { windKn: 8, seaState: 1 },
    comms: [{ at: iso(ago(58)), by: envOfficer.name, channel: 'EMAIL', direction: 'IN', message: 'Shift report received; near miss logged and classified.' }], documents: [{ name: 'shift-report-extract.pdf', docType: 'REPORT', sizeKB: 120, uploadedBy: envOfficer.name, at: iso(ago(58)), note: '' }],
    tasks: [task('Confirm banksman roster for reversing operations', envOfficer, ago(30), ago(34))], statusHistory: [hist('', 'OPEN', ago(60), 'HSE desk', 'Logged'), hist('OPEN', 'RESOLVED', ago(34), envOfficer.name, 'Toolbox talk held; banksman roster confirmed'), hist('RESOLVED', 'CLOSED', ago(26), envOfficer.name)],
    rca: { rootCause: 'Reversing without a banksman during a shift change', category: 'Procedure', correctiveAction: 'Banksman coverage made explicit in the shift handover checklist', preventiveAction: 'Reversing-alarm audit across terminal plant' }, outcome: 'No injury. Banksman coverage corrected at handover.' }));
  out.push(live({ category: 'NAVIGATION', type: 'NAV_HAZARD', severity: 'MEDIUM', status: 'MONITORING', title: 'Drifting 20-ft container reported in the southern approaches', description: 'AIS safety-related message from a transiting bulk carrier; corroborated by the surveillance zone-entry watch. Position drifting SE at about 0.4 kn. Survey launch tasked to verify and mark.',
    vesselName: 'Reported by transiting traffic', location: { area: fairway[0], lat: fairway[1] - 0.05, lon: fairway[2] - 0.03 }, reportedAt: iso(ago(26)), reportedBy: 'AIS safety-related message', source: 'AIS', assignedToId: dutyLead.id, assignedTo: dutyLead.name, assets: ['Survey launch SVL-01'],
    comms: [{ at: iso(ago(25.6)), by: dutyLead.name, channel: 'AIS', direction: 'IN', message: 'Safety-related message logged; position plotted on the surveillance picture.' }, { at: iso(ago(24)), by: dutyLead.name, channel: 'VHF', direction: 'OUT', message: 'Navigational warning broadcast to traffic in the southern approaches.' }],
    tasks: [task('Verify, mark or recover the container', dutyLead, new Date(now.getTime() + 10 * H), null)], log: [{ at: iso(ago(26)), by: 'Marine control room', entry: 'Hazard logged from an AIS safety-related message' }, { at: iso(ago(24)), by: dutyLead.name, entry: 'Navigational warning broadcast; survey launch tasked for first light' }],
    statusHistory: [hist('', 'OPEN', ago(26), 'Marine control room', 'Logged'), hist('OPEN', 'ACKNOWLEDGED', ago(25.5), dutyLead.name, 'Watch accepted; warning to be broadcast'), hist('ACKNOWLEDGED', 'RESPONDING', ago(24), dutyLead.name, 'Warning broadcast; survey launch tasked'), hist('RESPONDING', 'MONITORING', ago(20), dutyLead.name, 'Under watch until verified and recovered')] }));
  out.push(live({ category: 'MARINE', type: 'SAR', severity: 'HIGH', status: 'RESPONDING', title: 'Fishing vessel adrift with a fouled propeller, 6 nm SW of the fairway buoy', description: 'VHF Ch 16 distress relay; six crew on board, vessel drifting SW at 1.2 kn. Tow arranged.',
    vesselName: `FV ${fvNames[0]} (FV-REG-1287)`, location: { area: fairway[0], lat: fairway[1], lon: fairway[2] }, reportedAt: iso(ago(5)), reportedBy: 'VHF Ch 16 watch', source: 'VHF', assignedToId: dutyLead.id, assignedTo: dutyLead.name, assets: ['Tug TUG-01', 'Pilot launch PLT-02'], weather: { windKn: 18, seaState: 3 },
    comms: [{ at: iso(ago(4.8)), by: dutyLead.name, channel: 'VHF', direction: 'IN', message: 'Distress relay received; position plotted; boat drifting SW at 1.2 kn.' }, { at: iso(ago(4.4)), by: dutyLead.name, channel: 'PHONE', direction: 'OUT', message: 'Coast guard station informed; reference number logged.' }, { at: iso(ago(2)), by: 'Tug master', channel: 'VHF', direction: 'IN', message: 'Tow connected; proceeding to the fishing harbour; all six crew safe.' }],
    documents: [{ name: 'distress-relay-log.pdf', docType: 'REPORT', sizeKB: 240, uploadedBy: dutyLead.name, at: iso(ago(4)), note: '' }], tasks: [task('Notify the coast guard station', dutyLead, ago(4), ago(4.4)), task('Escort tow to the fishing harbour', dutyLead, new Date(now.getTime() + 2 * H), null)],
    log: [{ at: iso(ago(5)), by: 'Marine control room', entry: 'Incident logged; duty officer paged' }, { at: iso(ago(4.6)), by: dutyLead.name, entry: 'Tug TUG-01 tasked; ETA 45 min' }],
    statusHistory: [hist('', 'OPEN', ago(5), 'Marine control room', 'Incident logged'), hist('OPEN', 'ACKNOWLEDGED', ago(4.9), dutyLead.name), hist('ACKNOWLEDGED', 'RESPONDING', ago(4.6), dutyLead.name, 'Tug tasked')] }));
  out.push(live({ category: 'ENVIRONMENT', type: 'OIL_SPILL', severity: 'MEDIUM', status: 'OPEN', title: 'Light sheen observed near LB-2 during hose disconnection', description: 'Sheen approximately 15 m × 40 m reported alongside during hose disconnection. Tier-1 response readied.',
    vesselId: liquidCall ? vByName.get(liquidCall.vesselName)?.id ?? null : null, vesselName: liquidCall?.vesselName ?? '', berthId: lb2?.id ?? null, berthCode: 'LB-2', location: { area: 'LB-2', lat: geo.berthPos['LB-2'][0], lon: geo.berthPos['LB-2'][1] }, reportedAt: iso(ago(1.5)), reportedBy: 'Jetty supervisor', source: 'PHONE',
    assignedToId: envOfficer.id, assignedTo: envOfficer.name, assets: ['Boom crew A'], pollutionTier: 1, weather: { windKn: 9, seaState: 2 }, comms: [{ at: iso(ago(1.4)), by: envOfficer.name, channel: 'PORTAL', direction: 'INTERNAL', message: 'Tier-1 response activated; boom deployed as a precaution; sample taken for analysis.' }],
    tasks: [task('Collect water samples for analysis', envOfficer, new Date(now.getTime() + 4 * H), null), task('Obtain master\'s statement via agent', hse[1] ?? envOfficer, new Date(now.getTime() + 24 * H), null)], statusHistory: [hist('', 'OPEN', ago(1.5), 'Marine control room', 'Incident logged')] }));
  out.push(live({ category: 'SECURITY', type: 'SECURITY_BREACH', severity: 'MEDIUM', status: 'ACKNOWLEDGED', title: 'Unauthorised drone sighting over the CT-4 yard', description: 'Gate 3 patrol observed a small drone over the container yard for about four minutes; operator not located. Logged under the port facility security plan.',
    location: { area: 'CT-4 yard', lat: geo.berthPos['CT4-1'][0] + 0.002, lon: geo.berthPos['CT4-1'][1] }, reportedAt: iso(ago(9)), reportedBy: 'ISPS patrol — Gate 3', source: 'PATROL', assignedToId: pfso.id, assignedTo: pfso.name, weather: { windKn: 7, seaState: 1 },
    comms: [{ at: iso(ago(8.7)), by: pfso.name, channel: 'PORTAL', direction: 'INTERNAL', message: 'Patrol report logged; CCTV of the yard perimeter requested for the period.' }], tasks: [task('Review CCTV footage of the period', pfso, new Date(now.getTime() + 12 * H), null)],
    statusHistory: [hist('', 'OPEN', ago(9), 'Marine control room', 'Logged from the patrol report'), hist('OPEN', 'ACKNOWLEDGED', ago(8.7), pfso.name, 'Under the PFSO')] }));
  out.push(live({ category: 'EQUIPMENT', type: 'EQUIPMENT_FAILURE', severity: 'HIGH', status: 'RESPONDING', title: 'STS crane boom-limit fault at CT4-1 — crane taken out of service', description: 'Boom hoist stopped on a limit fault mid-cycle; spreader landed safely. Crane isolated and the technician called out; vessel working continues on the adjacent crane.',
    berthId: ct41?.id ?? null, berthCode: 'CT4-1', location: { area: 'CT4-1', lat: geo.berthPos['CT4-1'][0], lon: geo.berthPos['CT4-1'][1] }, reportedAt: iso(ago(3)), reportedBy: 'Crane operator', source: 'PORTAL', assignedToId: (hse[1] ?? chiefHse).id, assignedTo: (hse[1] ?? chiefHse).name, assets: ['Crane technician on call'],
    comms: [{ at: iso(ago(2.8)), by: (hse[1] ?? chiefHse).name, channel: 'PORTAL', direction: 'INTERNAL', message: 'Crane isolated and tagged out; permit to work raised for the technician.' }], tasks: [task('Isolate equipment and tag out', hse[1] ?? chiefHse, ago(2.5), ago(2.8)), task('Crane technician to test limit circuit', hse[1] ?? chiefHse, new Date(now.getTime() + 6 * H), null)],
    statusHistory: [hist('', 'OPEN', ago(3), 'Marine control room', 'Logged by the crane operator'), hist('OPEN', 'ACKNOWLEDGED', ago(2.9), (hse[1] ?? chiefHse).name), hist('ACKNOWLEDGED', 'RESPONDING', ago(2.8), (hse[1] ?? chiefHse).name, 'Crane isolated; technician called')] }));
  const evac = berthedNow[1] ?? berthedNow[0]; const evacOfficer = marine[0] ?? dutyLead;
  out.push(live({ category: 'PERSONNEL', type: 'MEDICAL_EVAC', severity: 'HIGH', status: 'RESOLVED', title: `Medical evacuation — crew member with chest pain on ${evac?.vesselName ?? 'a berthed vessel'}`, description: 'Second engineer reported chest pain during cargo watch; port ambulance attended at the gangway and the seafarer was taken to hospital. Stable.',
    vesselId: evac ? vByName.get(evac.vesselName)?.id ?? null : null, vesselName: evac?.vesselName ?? '', berthId: evac ? bByCode.get(evac.berthCode ?? '')?.id ?? null : null, berthCode: evac?.berthCode ?? '', location: { area: evac?.berthCode ?? geo.areas[3][0], lat: geo.berthPos[evac?.berthCode ?? '']?.[0] ?? geo.areas[3][1], lon: geo.berthPos[evac?.berthCode ?? '']?.[1] ?? geo.areas[3][2] },
    reportedAt: iso(ago(14)), reportedBy: 'Master via agent', source: 'PHONE', assignedToId: evacOfficer.id, assignedTo: evacOfficer.name, assets: ['Port ambulance'], injuries: 1,
    comms: [{ at: iso(ago(13.8)), by: evacOfficer.name, channel: 'PHONE', direction: 'OUT', message: 'Port ambulance dispatched to the gangway; agent informed.' }, { at: iso(ago(11)), by: 'Agent', channel: 'PHONE', direction: 'IN', message: 'Hospital confirms the seafarer is stable and under observation.' }],
    tasks: [task('Arrange ambulance and first aid', evacOfficer, ago(13.5), ago(13.8)), task('File P&I / insurance notification', evacOfficer, ago(2), ago(6))],
    statusHistory: [hist('', 'OPEN', ago(14), 'Marine control room', 'Logged'), hist('OPEN', 'RESPONDING', ago(13.8), evacOfficer.name, 'Ambulance dispatched'), hist('RESPONDING', 'RESOLVED', ago(10), evacOfficer.name, 'Seafarer in hospital and stable; relief crew member requested')],
    rca: { rootCause: 'Medical condition — no operational cause', category: 'Human factor', correctiveAction: 'Seafarer repatriated on medical grounds', preventiveAction: 'None arising' }, outcome: 'Seafarer stable; repatriation arranged by the manager.' }));
  const seq = makeSeries();
  out.sort((a, b) => a.reportedAt.localeCompare(b.reportedAt)).forEach((x) => { const y = yearOf(x.reportedAt); x.number = `INC-${y}-${seq(String(y))}`; x.id = stableId('incident', x.number); });
  return out;
}
