import { getJurisdiction, INSTRUMENT_TYPES, INSTRUMENT_STATUS } from '@maritime/contracts';
import { Prng, D, H, HIST_START, stableId, iso } from './prng';
import { usersByRole, type WorldUser } from './people';
import { tariffCircularRef } from './finance';

export type LegalInstrumentType = (typeof INSTRUMENT_TYPES)[number];
export type LegalInstrumentStatus = (typeof INSTRUMENT_STATUS)[number];
export interface WorldLegalInstrument {
  id: string; refNo: string; title: string; titleAr?: string; type: LegalInstrumentType; category: string; status: LegalInstrumentStatus; issuedBy: string; issuedDate: string; effectiveDate: string | null;
  summary: string; body: string; tags: string[]; supersedes: string; ackRequired: boolean; acknowledgedBy: { userId: string; name: string; at: string }[];
  draftedById: string; draftedBy: string; approvedById: string | null; approvedBy: string; approvedAt: string | null; sourceNote: string;
}
interface Def { refNo: string; title: string; titleAr?: string; type: LegalInstrumentType; category: string; status: LegalInstrumentStatus; issuedBy: string; issued: string | number; effective?: string | number | null; summary: string; body?: string; tags: string[]; supersedes?: string; ackRequired?: boolean; draftedByApprover?: boolean; sourceNote?: string }

// the international instruments every profile carries
const CONVENTIONS: Def[] = [
  { refNo: 'SOLAS-74', title: 'International Convention for the Safety of Life at Sea (SOLAS), 1974', titleAr: 'الاتفاقية الدولية لسلامة الأرواح في البحار 1974', type: 'CONVENTION', category: 'Safety', status: 'IN_FORCE', issuedBy: 'IMO', issued: '1974-11-01', effective: '1980-05-25', summary: 'Core IMO convention on ship safety — construction, fire protection, life-saving, radio, navigation.', tags: ['imo', 'safety'] },
  { refNo: 'MARPOL-73/78', title: 'International Convention for the Prevention of Pollution from Ships (MARPOL)', titleAr: 'الاتفاقية الدولية لمنع التلوث من السفن', type: 'CONVENTION', category: 'Environment', status: 'IN_FORCE', issuedBy: 'IMO', issued: '1973-11-02', effective: '1983-10-02', summary: 'Annexes I-VI: oil, chemicals, packaged goods, sewage, garbage and air emissions from ships.', tags: ['imo', 'environment'] },
  { refNo: 'STCW-78', title: 'International Convention on Standards of Training, Certification and Watchkeeping (STCW)', titleAr: 'الاتفاقية الدولية لمعايير التدريب والإجازة والمراقبة للملاحين', type: 'CONVENTION', category: 'Crew', status: 'IN_FORCE', issuedBy: 'IMO', issued: '1978-07-07', effective: '1984-04-28', summary: 'Competency standards, certification and watchkeeping arrangements for seafarers, as amended at Manila in 2010.', tags: ['imo', 'stcw', 'crew'] },
  { refNo: 'MLC-2006', title: 'Maritime Labour Convention, 2006', titleAr: 'اتفاقية العمل البحري 2006', type: 'CONVENTION', category: 'Crew', status: 'IN_FORCE', issuedBy: 'ILO', issued: '2006-02-23', effective: '2013-08-20', summary: 'Minimum conditions of employment, hours of work and rest, accommodation, medical care and social protection for seafarers.', tags: ['ilo', 'crew', 'welfare'] },
  { refNo: 'FAL-65', title: 'Convention on Facilitation of International Maritime Traffic (FAL), 1965', titleAr: 'اتفاقية تسهيل حركة الملاحة البحرية الدولية 1965', type: 'CONVENTION', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'IMO', issued: '1965-04-09', effective: '1967-03-05', summary: 'Standardised declarations and electronic single-window arrangements for ship arrival, stay and departure.', tags: ['imo', 'fal', 'single-window'] },
  { refNo: 'LL-66', title: 'International Convention on Load Lines, 1966', titleAr: 'الاتفاقية الدولية لخطوط الشحن 1966', type: 'CONVENTION', category: 'Safety', status: 'IN_FORCE', issuedBy: 'IMO', issued: '1966-04-05', effective: '1968-07-21', summary: 'Freeboard assignment, load line marks and the conditions of assignment surveyed through the term.', tags: ['imo', 'safety', 'load-line'] },
  { refNo: 'TONNAGE-69', title: 'International Convention on Tonnage Measurement of Ships, 1969', titleAr: 'الاتفاقية الدولية لقياس حمولة السفن 1969', type: 'CONVENTION', category: 'Principal legislation', status: 'IN_FORCE', issuedBy: 'IMO', issued: '1969-06-23', effective: '1982-07-18', summary: 'Gross and net tonnage as the universal basis for dues, manning and certification thresholds.', tags: ['imo', 'tonnage'] },
  { refNo: 'COLREG-72', title: 'Convention on the International Regulations for Preventing Collisions at Sea, 1972', titleAr: 'اتفاقية القواعد الدولية لمنع التصادم في البحار 1972', type: 'CONVENTION', category: 'Safety', status: 'IN_FORCE', issuedBy: 'IMO', issued: '1972-10-20', effective: '1977-07-15', summary: 'Steering and sailing rules, lights, shapes and sound signals.', tags: ['imo', 'navigation'] },
  { refNo: 'SAR-79', title: 'International Convention on Maritime Search and Rescue, 1979', titleAr: 'الاتفاقية الدولية للبحث والإنقاذ البحري 1979', type: 'CONVENTION', category: 'Safety', status: 'IN_FORCE', issuedBy: 'IMO', issued: '1979-04-27', effective: '1985-06-22', summary: 'Search and rescue regions, rescue coordination centres and cooperation between administrations.', tags: ['imo', 'sar'] },
  { refNo: 'BWM-2004', title: 'International Convention for the Control and Management of Ships\' Ballast Water and Sediments, 2004', titleAr: 'الاتفاقية الدولية لمراقبة وإدارة مياه صابورة السفن ورواسبها 2004', type: 'CONVENTION', category: 'Environment', status: 'IN_FORCE', issuedBy: 'IMO', issued: '2004-02-13', effective: '2017-09-08', summary: 'Ballast water management plans, record books and the D-2 discharge standard.', tags: ['imo', 'environment', 'bwm'] },
  { refNo: 'AFS-2001', title: 'International Convention on the Control of Harmful Anti-fouling Systems on Ships, 2001', titleAr: 'الاتفاقية الدولية لمراقبة أنظمة مكافحة الحشف الضارة على السفن 2001', type: 'CONVENTION', category: 'Environment', status: 'IN_FORCE', issuedBy: 'IMO', issued: '2001-10-05', effective: '2008-09-17', summary: 'Prohibition of harmful organotin compounds in anti-fouling paints and the AFS certificate.', tags: ['imo', 'environment'] },
  { refNo: 'CLC-92', title: 'International Convention on Civil Liability for Oil Pollution Damage, 1992', titleAr: 'الاتفاقية الدولية للمسؤولية المدنية عن أضرار التلوث الزيتي 1992', type: 'CONVENTION', category: 'Environment', status: 'IN_FORCE', issuedBy: 'IMO', issued: '1992-11-27', effective: '1996-05-30', summary: 'Strict liability of the owner for oil pollution damage and the compulsory insurance certificate.', tags: ['imo', 'liability'] },
  { refNo: 'BUNKER-2001', title: 'International Convention on Civil Liability for Bunker Oil Pollution Damage, 2001', titleAr: 'الاتفاقية الدولية للمسؤولية المدنية عن أضرار التلوث بزيت الوقود 2001', type: 'CONVENTION', category: 'Environment', status: 'IN_FORCE', issuedBy: 'IMO', issued: '2001-03-23', effective: '2008-11-21', summary: 'Liability and compulsory insurance for pollution damage caused by bunker oil.', tags: ['imo', 'liability'] },
  { refNo: 'WRC-2007', title: 'Nairobi International Convention on the Removal of Wrecks, 2007', titleAr: 'اتفاقية نيروبي الدولية لإزالة الحطام 2007', type: 'CONVENTION', category: 'Environment', status: 'IN_FORCE', issuedBy: 'IMO', issued: '2007-05-18', effective: '2015-04-14', summary: 'Owner liability for locating, marking and removing wrecks, with compulsory insurance.', tags: ['imo', 'liability', 'wreck'] },
];

// the profile's own statute book: acts and rules, chains that show supersession, and the standing circulars, notices and orders. Days are offsets from "now".
const PROFILE: Record<string, Def[]> = {
  AE: [
    { refNo: 'FDL-43/2023', title: 'Federal Decree-Law No. 43 of 2023 Concerning Maritime Law', titleAr: 'مرسوم بقانون اتحادي رقم 43 لسنة 2023 في شأن القانون البحري', type: 'ACT', category: 'Principal legislation', status: 'IN_FORCE', issuedBy: 'Federal Government', issued: '2023-10-02', effective: '2024-03-29',
      summary: 'Principal maritime statute — registration, nationality of ships, mortgages, safety, crew and liability. Replaces the 1981 Commercial Maritime Law.', tags: ['statute', 'registration', 'crew'], supersedes: 'FL-26/1981', sourceNote: 'Issue and commencement dates to be verified against the Official Gazette before go-live.' },
    { refNo: 'FL-26/1981', title: 'Federal Law No. 26 of 1981 (Commercial Maritime Law)', titleAr: 'قانون اتحادي رقم 26 لسنة 1981 في شأن القانون التجاري البحري', type: 'ACT', category: 'Principal legislation', status: 'SUPERSEDED', issuedBy: 'Federal Government', issued: '1981-12-02', effective: '1982-01-01',
      summary: 'The former commercial maritime code, superseded by Federal Decree-Law No. 43 of 2023.', tags: ['statute'], sourceNote: 'Dates to be verified before go-live.' },
    { refNo: 'MSA-R-01/2024', title: 'Ship Registration Regulation — implementing decisions under the Maritime Law', titleAr: 'لائحة تسجيل السفن — القرارات التنفيذية للقانون البحري', type: 'RULES', category: 'Principal legislation', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -880, effective: -850, summary: 'Procedure for provisional and permanent registration, carving and marking, transfer, mortgage and closure of registry.', tags: ['registration'] },
    { refNo: 'MSA-R-02/2024', title: 'Survey and Certification Regulation', titleAr: 'لائحة المعاينة وإصدار الشهادات', type: 'RULES', category: 'Safety', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -840, effective: -810, summary: 'Initial, annual, intermediate and renewal survey regime and the endorsement of statutory certificates.', tags: ['survey', 'certification'] },
    { refNo: 'MSA-R-03/2024', title: 'Seafarer Certification (STCW) Regulation', titleAr: 'لائحة إجازة الملاحين (STCW)', type: 'RULES', category: 'Crew', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -800, effective: -770, summary: 'National implementation of STCW 2010 (Manila amendments) — competency, certification, endorsement and watchkeeping.', tags: ['stcw', 'crew'] },
    { refNo: 'MSA-R-04/2024', title: 'Maritime Facilities and Companies Licensing Regulation', titleAr: 'لائحة ترخيص المنشآت والشركات البحرية', type: 'RULES', category: 'Licensing', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -760, effective: -730, summary: 'Licence categories, conditions and audit intervals for agencies, suppliers, yards, surveyors and training institutes.', tags: ['licensing', 'facilities'] },
    { refNo: 'MSA-R-05/2024', title: 'Port Facility Security (ISPS) Regulation', titleAr: 'لائحة أمن المرافق المينائية (ISPS)', type: 'RULES', category: 'Security', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -720, effective: -690, summary: 'Port facility security assessments, plans, PFSO appointment and the statement of compliance.', tags: ['isps', 'security'] },
    { refNo: 'MSA-R-06/2025', title: 'Marine Casualty Investigation Regulation', titleAr: 'لائحة التحقيق في الحوادث البحرية', type: 'RULES', category: 'Safety', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -420, effective: -390, summary: 'Reporting thresholds, investigation authority and publication of casualty reports under the IMO Casualty Investigation Code.', tags: ['casualty', 'investigation'] },
    { refNo: 'MSA-CIRC-07/2023', title: 'Container VGM declaration — interim procedure', titleAr: 'إقرار الكتلة الإجمالية المحققة للحاويات — إجراء مؤقت', type: 'CIRCULAR', category: 'Port operations', status: 'SUPERSEDED', issuedBy: 'Port Operations', issued: '2023-03-18', effective: '2023-04-01', summary: 'First interim arrangement for Verified Gross Mass declarations, pending weighbridge commissioning.', tags: ['solas', 'vgm', 'container'] },
    { refNo: 'MSA-CIRC-07/2024', title: 'Container VGM verification procedure at the gate', titleAr: 'إجراء التحقق من الكتلة الإجمالية للحاويات عند البوابة', type: 'CIRCULAR', category: 'Port operations', status: 'SUPERSEDED', issuedBy: 'Port Operations', issued: '2024-03-18', effective: '2024-04-01', summary: 'Verified Gross Mass to be declared and weighed at the terminal gate for all export containers per SOLAS Ch VI reg 2.',
      body: 'Shipping agents and customs brokers shall submit VGM via Method 1 (weighing the packed container) at the terminal gate weighbridge; Method 2 (calculated) declarations must carry the shipper\'s certified weighing procedure on file. Containers without a VGM record on file will not be permitted to load.', supersedes: 'MSA-CIRC-07/2023', tags: ['solas', 'vgm', 'container'] },
    { refNo: 'MSA-CIRC-05/2026', title: 'Container VGM — automated weighbridge capture and tolerance', titleAr: 'الكتلة الإجمالية للحاويات — الالتقاط الآلي بالميزان الجسري وهامش التفاوت', type: 'CIRCULAR', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Port Operations', issued: -55, effective: -25, summary: 'VGM captured automatically at the gate weighbridge; a 500 kg tolerance applies against the declared figure, above which the container is held.',
      body: 'From the effective date the terminal gate weighbridge writes the Verified Gross Mass directly to the container record. Where the weighed figure differs from the declared figure by more than 500 kg, the container is held and the agent notified for re-declaration.', supersedes: 'MSA-CIRC-07/2024', tags: ['solas', 'vgm', 'container'], ackRequired: true },
    { refNo: 'MSA-CIRC-03/2023', title: 'Pre-arrival notification format revised — IMO FAL forms', titleAr: 'تعديل نموذج الإخطار قبل الوصول — نماذج FAL', type: 'CIRCULAR', category: 'Port operations', status: 'SUPERSEDED', issuedBy: 'Port Operations', issued: '2023-09-04', effective: '2023-10-01', summary: 'Interim FAL format ahead of the maritime single-window rollout.', tags: ['fal', 'pre-arrival'] },
    { refNo: 'MSA-CIRC-12/2026', title: 'Electronic port clearance — mandatory FAL declarations via the maritime single window', titleAr: 'التخليص الإلكتروني — إلزامية إقرارات FAL عبر النافذة البحرية الموحدة', type: 'CIRCULAR', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Port Operations', issued: -40, effective: -10, summary: 'All agents to submit FAL 1-7 declarations electronically; paper submissions cease from the effective date.',
      body: 'Pursuant to the FAL Convention (2022 amendments), all shipping agents shall lodge General Declaration, Cargo Declaration, Ship Stores, Crew Effects, Crew List, Passenger List and Dangerous Goods declarations through the maritime single window.', supersedes: 'MSA-CIRC-03/2023', tags: ['fal', 'single-window'], ackRequired: true },
    { refNo: 'HM-CIRC-04/2025', title: 'Anchorage allocation policy — priority matrix', titleAr: 'سياسة تخصيص المرسى — مصفوفة الأولويات', type: 'CIRCULAR', category: 'Port operations', status: 'SUPERSEDED', issuedBy: 'Harbour Master', issued: -400, effective: -380, summary: 'Priority matrix for anchorage allocation by vessel class, cargo and declared readiness.', tags: ['anchorage'] },
    { refNo: 'PORT-N-07/2026', title: 'Summer shamal working restrictions — West Basin and outer anchorage', titleAr: 'قيود العمل خلال رياح الشمال الصيفية — الحوض الغربي والمرسى الخارجي', type: 'NOTICE', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -70, effective: -60, summary: 'Cape vessels to maintain 20% additional UKC at WB berths during shamal conditions; bunkering suspended at the outer anchorage above sea state 5.',
      body: 'During shamal conditions all capesize vessels berthing at WB-1/WB-2 shall maintain an additional 20% under-keel clearance over the declared minimum. Bunker barge operations at the outer anchorage stand suspended whenever sea state exceeds 5 or wind exceeds 25 knots sustained.', supersedes: 'HM-CIRC-04/2025', tags: ['shamal', 'ukc', 'bunkering'], ackRequired: true },
    { refNo: 'FIN-CIRC-09/2026', title: 'Revised garbage reception fees under MARPOL Annex V', titleAr: 'مراجعة رسوم استقبال النفايات بموجب الملحق الخامس من ماربول', type: 'CIRCULAR', category: 'Tariff', status: 'IN_FORCE', issuedBy: 'Finance Directorate', issued: -120, effective: -90, summary: 'Garbage reception charge revised; segregation certificate required from vessels landing more than 2 cubic metres.', tags: ['marpol', 'tariff'] },
    // a legacy conflict of the kind every library carries: the 2024 schedule was never marked superseded, so both are in force on the same subject
    { refNo: 'FIN-CIRC-09/2024', title: 'Garbage reception fees — revised schedule', titleAr: 'رسوم استقبال النفايات — الجدول المعدل', type: 'CIRCULAR', category: 'Tariff', status: 'IN_FORCE', issuedBy: 'Finance Directorate', issued: '2024-05-14', effective: '2024-06-01', summary: 'Garbage reception charge schedule by volume band and waste stream, with the segregation certificate requirement.', tags: ['marpol', 'tariff'] },
    { refNo: 'MSA-CIRC-01/2024', title: 'Crew change procedures at ports of the State', titleAr: 'إجراءات تبديل الأطقم في موانئ الدولة', type: 'CIRCULAR', category: 'Crew', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -960, effective: -940, summary: 'Notification, documentation and transit arrangements for crew joining and leaving ships in port.', tags: ['crew', 'crew-change'], ackRequired: true },
    { refNo: 'MSA-CIRC-04/2024', title: 'Bunkering operations — licensed suppliers and reporting', titleAr: 'عمليات التزود بالوقود — الموردون المرخصون والإبلاغ', type: 'CIRCULAR', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -820, effective: -790, summary: 'Only licensed suppliers may deliver bunkers; bunker delivery notes to be reported through the portal within 24 hours.', tags: ['bunkering', 'licensing'] },
    { refNo: 'MSA-CIRC-06/2024', title: 'Maritime cyber-security — minimum measures for ships and port facilities', titleAr: 'الأمن السيبراني البحري — الحد الأدنى من التدابير للسفن والمرافق المينائية', type: 'CIRCULAR', category: 'Security', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -700, effective: -640, summary: 'Cyber risk management to be addressed in safety management systems and port facility security plans.', tags: ['cyber', 'isps', 'ism'], ackRequired: true },
    { refNo: 'MSA-CIRC-02/2025', title: 'Electronic certificates — acceptance of e-certificates issued by recognised organisations', titleAr: 'الشهادات الإلكترونية — قبول الشهادات الصادرة عن الهيئات المعترف بها', type: 'CIRCULAR', category: 'Safety', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -520, effective: -490, summary: 'Electronic statutory certificates with a verifiable signature are accepted on board in place of paper originals.', tags: ['certification', 'e-certificate'] },
    { refNo: 'MSA-CIRC-05/2025', title: 'Ballast water record book inspection focus', titleAr: 'التركيز على تفتيش سجل مياه الصابورة', type: 'CIRCULAR', category: 'Environment', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -150, effective: -130, summary: 'Concentrated inspection of ballast water management plans and record books, aligned to the BWM Convention.', tags: ['bwm', 'environment', 'inspection'], ackRequired: true },
    { refNo: 'MSA-CIRC-08/2025', title: 'Seafarer medical certificates — approved medical practitioners', titleAr: 'الشهادات الطبية للملاحين — الأطباء المعتمدون', type: 'CIRCULAR', category: 'Crew', status: 'IN_FORCE', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -300, effective: -270, summary: 'Medical fitness certificates are accepted only from practitioners on the approved list; the list is published quarterly.', tags: ['crew', 'medical', 'mlc'] },
    { refNo: 'ISPS-ADV-02/2026', title: 'Security level 1 in force — access control reminders', titleAr: 'مستوى الأمن 1 ساري — تذكير بضوابط الدخول', type: 'ORDER', category: 'Security', status: 'IN_FORCE', issuedBy: 'Port Facility Security Officer', issued: -15, effective: -15, summary: 'Security Level 1 continues; dock passes to be displayed; crew shore leave via Gate 3 only.', tags: ['isps', 'security'] },
    { refNo: 'HM-ORD-02/2026', title: 'Designation of authorised bunker supply points', titleAr: 'تحديد نقاط التزود بالوقود المعتمدة', type: 'ORDER', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -200, effective: -180, summary: 'Bunkering permitted only at designated berths and the inner anchorage, and only by licensed suppliers.', tags: ['bunkering', 'licensing'] },
    { refNo: 'HM-ORD-01/2024', title: 'Speed restriction in the approach channel — 8 knots', titleAr: 'تقييد السرعة في قناة الاقتراب — 8 عقد', type: 'ORDER', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -900, effective: -880, summary: 'Speed through the water limited to 8 knots inside the approach channel; the surveillance centre records exceedances.', tags: ['navigation', 'speed'] },
    { refNo: 'HM-ORD-03/2025', title: 'Designation of anchorage areas A1 to A3', titleAr: 'تحديد مناطق المرسى A1 إلى A3', type: 'ORDER', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -500, effective: -470, summary: 'Anchorage areas defined by vessel class and cargo; anchoring outside the designated areas requires permission.', tags: ['anchorage'] },
    { refNo: 'NOTICE-04/2026', title: 'Navigational warning — survey operations, outer approach channel', titleAr: 'تحذير ملاحي — أعمال مسح في قناة الاقتراب الخارجية', type: 'NOTICE', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -8, effective: -8, summary: 'Hydrographic survey vessel operating in the outer approach channel; wide berth requested and speed restricted to 8 knots within 1 nm.', tags: ['navigation', 'safety'] },
    { refNo: 'NOTICE-01/2025', title: 'Notice to mariners — revised channel buoyage', titleAr: 'إشعار للملاحين — تعديل عوامات القناة', type: 'NOTICE', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -560, effective: -540, summary: 'Lateral buoys 5 to 9 relocated following capital dredging; corrected chart extract attached.', tags: ['navigation', 'buoyage'] },
    { refNo: 'NOTICE-03/2024', title: 'Dredging works — approach channel, restricted passing', titleAr: 'أعمال التجريف — قناة الاقتراب، تقييد العبور', type: 'NOTICE', category: 'Port operations', status: 'WITHDRAWN', issuedBy: 'Harbour Master', issued: -700, effective: -690, summary: 'Trailing suction hopper dredger working the channel; one-way traffic under VTS control. Withdrawn on completion of the works.', tags: ['dredging', 'navigation'] },
    { refNo: 'PORT-N-02/2023', title: 'Severe shamal — berthing suspension and vessel evacuation', titleAr: 'رياح شمال شديدة — تعليق الرسو وإخلاء السفن', type: 'NOTICE', category: 'Port operations', status: 'WITHDRAWN', issuedBy: 'Harbour Master', issued: '2023-02-14', effective: '2023-02-15', summary: 'Precautionary berthing suspension ahead of a severe shamal. Withdrawn once the all-clear survey completed.', tags: ['weather', 'contingency'] },
    // drafted by the approver themselves — the case separation of duties exists for
    { refNo: 'NOTICE-06/2026', title: 'Draft navigational notice — revised pilot boarding ground', titleAr: 'مسودة إشعار ملاحي — تعديل منطقة صعود المرشد', type: 'NOTICE', category: 'Port operations', status: 'DRAFT', issuedBy: 'Harbour Master', issued: -2, effective: null, summary: 'Draft for approval: pilot boarding ground moved 1.2 nm seaward of the present position.', tags: ['pilotage', 'navigation'], draftedByApprover: true },
    { refNo: 'MSA-CIRC-14/2026', title: 'Shore power connection — phased mandatory use at container berths', titleAr: 'التوصيل بالطاقة الساحلية — الاستخدام الإلزامي التدريجي عند أرصفة الحاويات', type: 'CIRCULAR', category: 'Environment', status: 'DRAFT', issuedBy: 'Ministry of Energy and Infrastructure — Maritime Sector', issued: -3, effective: null, summary: 'Draft for consultation: phased mandatory shore power connection for container vessels alongside more than four hours.', tags: ['emissions', 'shore-power', 'consultation'] },
  ],
  IN: [
    { refNo: 'MSA-1958', title: 'Merchant Shipping Act, 1958 (as amended)', type: 'ACT', category: 'Principal legislation', status: 'IN_FORCE', issuedBy: 'National Legislature', issued: '1958-10-30', effective: '1959-01-01', summary: 'Principal statute governing merchant shipping — registration, certification, safety, crew and liability.', tags: ['statute', 'registration', 'crew'] },
    { refNo: 'IPA-1908', title: 'Indian Ports Act, 1908', type: 'ACT', category: 'Principal legislation', status: 'IN_FORCE', issuedBy: 'National Legislature', issued: '1908-12-18', effective: '1909-01-01', summary: 'Port limits, conservancy, port dues and the powers of the conservator.', tags: ['statute', 'ports'] },
    { refNo: 'IVA-2021', title: 'Inland Vessels Act, 2021', type: 'ACT', category: 'Principal legislation', status: 'IN_FORCE', issuedBy: 'National Legislature', issued: '2021-08-11', effective: '2022-02-16', summary: 'Uniform regulation of inland vessels — registration, survey, crew and navigation.', tags: ['statute', 'inland'] },
    { refNo: 'MS-STCW-RULES', title: 'Merchant Shipping (Standards of Training, Certification and Watchkeeping) Rules', type: 'RULES', category: 'Crew', status: 'IN_FORCE', issuedBy: 'Directorate General of Shipping', issued: '2014-06-20', effective: '2014-09-01', summary: 'National implementation of STCW 2010 (Manila amendments) — competency, certification and watchkeeping.', tags: ['stcw', 'crew'] },
    { refNo: 'MS-REG-RULES', title: 'Merchant Shipping (Registration of Ships) Rules', type: 'RULES', category: 'Principal legislation', status: 'IN_FORCE', issuedBy: 'Directorate General of Shipping', issued: '2016-02-11', effective: '2016-04-01', summary: 'Procedure for provisional and permanent registration, carving and marking, transfer, mortgage and closure of registry.', tags: ['registration'] },
    { refNo: 'MS-SURVEY-RULES', title: 'Merchant Shipping (Survey and Certification) Rules', type: 'RULES', category: 'Safety', status: 'IN_FORCE', issuedBy: 'Directorate General of Shipping', issued: '2018-07-02', effective: '2018-10-01', summary: 'Initial, annual, intermediate and renewal survey regime and the endorsement of statutory certificates.', tags: ['survey', 'certification'] },
    { refNo: 'MS-MLC-RULES', title: 'Merchant Shipping (Maritime Labour) Rules, 2016', type: 'RULES', category: 'Crew', status: 'IN_FORCE', issuedBy: 'Directorate General of Shipping', issued: '2016-03-15', effective: '2016-04-01', summary: 'National implementation of MLC 2006 — employment agreements, hours of rest, accommodation and welfare.', tags: ['mlc', 'crew'] },
    { refNo: 'CIRC-07/2022', title: 'Container VGM declaration — interim procedure', type: 'CIRCULAR', category: 'Port operations', status: 'SUPERSEDED', issuedBy: 'Port Operations', issued: '2022-03-18', effective: '2022-04-01', summary: 'First interim arrangement for Verified Gross Mass declarations, pending weighbridge commissioning.', tags: ['solas', 'vgm', 'container'] },
    { refNo: 'CIRC-07/2024', title: 'Container VGM verification procedure at the gate', type: 'CIRCULAR', category: 'Port operations', status: 'SUPERSEDED', issuedBy: 'Port Operations', issued: '2024-03-18', effective: '2024-04-01', summary: 'Verified Gross Mass to be declared and weighed at the terminal gate for all export containers per SOLAS Ch VI reg 2.', supersedes: 'CIRC-07/2022', tags: ['solas', 'vgm', 'container'] },
    { refNo: 'CIRC-05/2026', title: 'Container VGM — automated weighbridge capture and tolerance', type: 'CIRCULAR', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Port Operations', issued: -55, effective: -25, summary: 'VGM captured automatically at the gate weighbridge; a 500 kg tolerance applies against the declared figure, above which the container is held.', supersedes: 'CIRC-07/2024', tags: ['solas', 'vgm', 'container'], ackRequired: true },
    { refNo: 'CIRC-03/2023', title: 'Pre-arrival notification format revised — IMO FAL forms', type: 'CIRCULAR', category: 'Port operations', status: 'SUPERSEDED', issuedBy: 'Port Operations', issued: '2023-09-04', effective: '2023-10-01', summary: 'Interim paper and email FAL format ahead of the single-window rollout.', tags: ['fal', 'pre-arrival'] },
    { refNo: 'CIRC-12/2026', title: 'Electronic port clearance — mandatory FAL declarations via portal', type: 'CIRCULAR', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Port Operations', issued: -40, effective: -10, summary: 'All agents to submit FAL 1-7 declarations electronically; paper submissions cease from the effective date.', supersedes: 'CIRC-03/2023', tags: ['fal', 'single-window'], ackRequired: true },
    { refNo: 'CIRC-04/2025', title: 'Anchorage allocation policy — priority matrix', type: 'CIRCULAR', category: 'Port operations', status: 'SUPERSEDED', issuedBy: 'Harbour Master', issued: -400, effective: -380, summary: 'Priority matrix for anchorage allocation by vessel class, cargo and declared readiness.', tags: ['anchorage'] },
    { refNo: 'PORT-N-07/2026', title: 'Monsoon working restrictions — West Basin and outer anchorage', type: 'NOTICE', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -70, effective: -60, summary: 'Cape vessels to maintain 20% additional UKC at WB berths during the SW monsoon; bunkering suspended at outer anchorage above sea state 5.', supersedes: 'CIRC-04/2025', tags: ['monsoon', 'ukc', 'bunkering'], ackRequired: true },
    { refNo: 'CIRC-09/2026', title: 'Revised garbage reception fees under MARPOL Annex V', type: 'CIRCULAR', category: 'Tariff', status: 'IN_FORCE', issuedBy: 'Finance Directorate', issued: -120, effective: -90, summary: 'Garbage reception charge revised; segregation certificate required from vessels landing more than 2 cubic metres.', tags: ['marpol', 'tariff'] },
    { refNo: 'CIRC-09/2024', title: 'Garbage reception fees — revised schedule', type: 'CIRCULAR', category: 'Tariff', status: 'IN_FORCE', issuedBy: 'Finance Directorate', issued: '2024-05-14', effective: '2024-06-01', summary: 'Garbage reception charge schedule by volume band and waste stream, with the segregation certificate requirement.', tags: ['marpol', 'tariff'] },
    { refNo: 'DGS-CIRC-01/2024', title: 'Crew change procedures at Indian ports', type: 'CIRCULAR', category: 'Crew', status: 'IN_FORCE', issuedBy: 'Directorate General of Shipping', issued: -960, effective: -940, summary: 'Notification, documentation and transit arrangements for crew joining and leaving ships in port.', tags: ['crew', 'crew-change'], ackRequired: true },
    { refNo: 'DGS-CIRC-06/2024', title: 'Maritime cyber-security — minimum measures for ships and port facilities', type: 'CIRCULAR', category: 'Security', status: 'IN_FORCE', issuedBy: 'Directorate General of Shipping', issued: -700, effective: -640, summary: 'Cyber risk management to be addressed in safety management systems and port facility security plans.', tags: ['cyber', 'isps', 'ism'], ackRequired: true },
    { refNo: 'DGS-CIRC-02/2025', title: 'Electronic certificates — acceptance of e-certificates issued by recognised organisations', type: 'CIRCULAR', category: 'Safety', status: 'IN_FORCE', issuedBy: 'Directorate General of Shipping', issued: -520, effective: -490, summary: 'Electronic statutory certificates with a verifiable signature are accepted on board in place of paper originals.', tags: ['certification', 'e-certificate'] },
    { refNo: 'CIRC-02/2026', title: 'Ballast water record book inspection focus', type: 'CIRCULAR', category: 'Environment', status: 'IN_FORCE', issuedBy: 'Directorate General of Shipping', issued: -150, effective: -130, summary: 'Concentrated inspection campaign on ballast water management plans and record books, aligned to the BWM Convention.', tags: ['bwm', 'environment', 'inspection'], ackRequired: true },
    { refNo: 'DGS-CIRC-08/2025', title: 'Seafarer medical certificates — approved medical examiners', type: 'CIRCULAR', category: 'Crew', status: 'IN_FORCE', issuedBy: 'Directorate General of Shipping', issued: -300, effective: -270, summary: 'Medical fitness certificates are accepted only from examiners on the approved list; the list is published quarterly.', tags: ['crew', 'medical', 'mlc'] },
    { refNo: 'ISPS-ADV-02/2026', title: 'Security level 1 in force — access control reminders', type: 'ORDER', category: 'Security', status: 'IN_FORCE', issuedBy: 'Port Facility Security Officer', issued: -15, effective: -15, summary: 'Security Level 1 continues; dock passes to be displayed; crew shore leave via Gate 3 only.', tags: ['isps', 'security'] },
    { refNo: 'ORD-02/2026', title: 'Designation of authorised bunker supply points', type: 'ORDER', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -200, effective: -180, summary: 'Bunkering permitted only at designated berths and the inner anchorage, and only by licensed suppliers holding a current facility licence.', tags: ['bunkering', 'licensing'] },
    { refNo: 'ORD-01/2024', title: 'Speed restriction in the approach channel — 8 knots', type: 'ORDER', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -900, effective: -880, summary: 'Speed through the water limited to 8 knots inside the approach channel.', tags: ['navigation', 'speed'] },
    { refNo: 'ORD-03/2025', title: 'Designation of anchorage areas A1 to A3', type: 'ORDER', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -500, effective: -470, summary: 'Anchorage areas defined by vessel class and cargo; anchoring outside the designated areas requires permission.', tags: ['anchorage'] },
    { refNo: 'NOTICE-04/2026', title: 'Navigational warning — survey operations, outer approach channel', type: 'NOTICE', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -8, effective: -8, summary: 'Hydrographic survey vessel operating in the outer approach channel; wide berth requested and speed restricted to 8 knots within 1 nm.', tags: ['navigation', 'safety'] },
    { refNo: 'NOTICE-01/2025', title: 'Notice to mariners — revised channel buoyage', type: 'NOTICE', category: 'Port operations', status: 'IN_FORCE', issuedBy: 'Harbour Master', issued: -560, effective: -540, summary: 'Lateral buoys 5 to 9 relocated following capital dredging; corrected chart extract attached.', tags: ['navigation', 'buoyage'] },
    { refNo: 'NOTICE-03/2024', title: 'Dredging works — approach channel, restricted passing', type: 'NOTICE', category: 'Port operations', status: 'WITHDRAWN', issuedBy: 'Harbour Master', issued: -700, effective: -690, summary: 'Trailing suction hopper dredger working the channel; one-way traffic under VTS control. Withdrawn on completion of the works.', tags: ['dredging', 'navigation'] },
    { refNo: 'PORT-N-02/2023', title: 'Tropical cyclone contingency — berthing restrictions and evacuation', type: 'NOTICE', category: 'Port operations', status: 'WITHDRAWN', issuedBy: 'Harbour Master', issued: '2023-06-12', effective: '2023-06-13', summary: 'Precautionary berthing suspension and vessel evacuation to sea ahead of a severe tropical cyclone. Withdrawn once the all-clear survey completed.', tags: ['cyclone', 'contingency', 'weather'] },
    { refNo: 'NOTICE-06/2026', title: 'Draft navigational notice — revised pilot boarding ground', type: 'NOTICE', category: 'Port operations', status: 'DRAFT', issuedBy: 'Harbour Master', issued: -2, effective: null, summary: 'Draft for approval: pilot boarding ground moved 1.2 nm seaward of the present position.', tags: ['pilotage', 'navigation'], draftedByApprover: true },
    { refNo: 'CIRC-14/2026', title: 'Shore power connection — phased mandatory use at container berths', type: 'CIRCULAR', category: 'Environment', status: 'DRAFT', issuedBy: 'Directorate General of Shipping', issued: -3, effective: null, summary: 'Draft for consultation: phased mandatory shore power connection for container vessels alongside more than four hours.', tags: ['emissions', 'shore-power', 'consultation'] },
  ],
};
// instruments reissued every year, so the register shows chains as chains: each edition supersedes the last
const YEARLY: Record<string, [string, string, string, string, number, number, string[], boolean][]> = { // prefix, title, Arabic title, category, issue month (0-based), issue day, tags, ackRequired
  AE: [['MSA-CIRC-HS', 'Summer working hours and heat-stress measures at port facilities', 'ساعات العمل الصيفية وتدابير الإجهاد الحراري في المرافق المينائية', 'Crew', 5, 10, ['heat-stress', 'welfare'], true],
    ['MSA-CIRC-RM', 'Ramadan working hours and gate arrangements', 'ساعات العمل في رمضان وترتيبات البوابات', 'Port operations', 1, 20, ['working-hours', 'gates'], false],
    ['MSA-CIRC-CIC', 'Concentrated inspection campaign — port state control focus', 'حملة التفتيش المركّزة — تركيز رقابة دولة الميناء', 'Safety', 7, 15, ['psc', 'inspection'], true],
    ['TAR-CIRC', 'Annual tariff revision — marine and cargo charges', 'المراجعة السنوية للتعرفة — الرسوم البحرية ورسوم البضائع', 'Tariff', 0, 1, ['tariff'], false]],
  IN: [['CIRC-MON', 'Pre-monsoon preparedness — mooring and cargo work', '', 'Port operations', 4, 15, ['monsoon', 'mooring'], true],
    ['CIRC-CYC', 'Cyclone season contingency arrangements', '', 'Port operations', 9, 1, ['cyclone', 'contingency'], false],
    ['CIRC-CIC', 'Concentrated inspection campaign — port state control focus', '', 'Safety', 7, 15, ['psc', 'inspection'], true],
    ['TAR-CIRC', 'Annual tariff revision — marine and cargo charges', '', 'Tariff', 3, 1, ['tariff'], false]],
};

/** ~60 instruments: conventions, the profile's acts and rules, supersession chains, drafts and withdrawals, with acknowledgement receipts on the mandatory circulars. */
export function buildLegalInstruments(rng: Prng, profile: string, users: WorldUser[], now: Date): WorldLegalInstrument[] {
  const j = getJurisdiction(profile); const ae = j.code === 'AE';
  const at = (v: string | number | null | undefined): Date | null => (v == null ? null : typeof v === 'number' ? new Date(now.getTime() + v * D) : new Date(`${v}T09:00:00Z`));
  const defs: Def[] = [...CONVENTIONS, ...(PROFILE[j.code] ?? PROFILE.AE)];
  for (const [prefix, title, titleAr, category, month, dayOfMonth, tags, ackRequired] of YEARLY[j.code] ?? YEARLY.AE) {
    let prev = '';
    for (let y = HIST_START.getUTCFullYear(); y <= now.getUTCFullYear(); y++) {
      const issued = new Date(Date.UTC(y, month, dayOfMonth, 9)); if (issued.getTime() > now.getTime()) break;
      const refNo = prefix === 'TAR-CIRC' ? tariffCircularRef(y) : `${prefix}-${String(y).slice(2)}/${y}`;
      defs.push({ refNo, title: `${title} — ${y}`, titleAr: ae ? `${titleAr} — ${y}` : undefined, type: 'CIRCULAR', category, status: 'IN_FORCE', issuedBy: prefix === 'TAR-CIRC' ? 'Finance Directorate' : ae ? 'Ministry of Energy and Infrastructure — Maritime Sector' : 'Directorate General of Shipping',
        issued: iso(issued).slice(0, 10), effective: iso(issued.getTime() + 14 * D).slice(0, 10), summary: `${title}, as applying for ${y}.${prev ? ` Supersedes the ${y - 1} edition.` : ''}`, tags, supersedes: prev, ackRequired });
      if (prev) { const p = defs.find((d) => d.refNo === prev); if (p) p.status = 'SUPERSEDED'; }
      prev = refNo;
    }
  }
  // publication governance: everything in force was drafted and approved by two different people; the drafts wait on an approver who is not their drafter
  const legal = usersByRole(users, 'Legal Officer')[0] ?? users[0]; const approver = usersByRole(users, 'Approver')[0] ?? users[1];
  const ackPool = users.filter((u) => u.active);
  return defs.map((d) => {
    const issuedDate = at(d.issued)!; const drafter = d.draftedByApprover ? approver : legal;
    const ageDays = Math.max(1, Math.round((now.getTime() - issuedDate.getTime()) / D));
    const reach = d.ackRequired ? Math.min(0.92, 0.18 + ageDays / 160) : 0; // older instruments have reached more of the roll
    const acknowledgedBy = ackPool.slice(0, Math.round(ackPool.length * reach)).map((u, i) => ({ userId: u.id, name: u.name, at: iso(issuedDate.getTime() + rng.int(2, 96) * H + i * 61000) }));
    return {
      id: stableId('instrument', d.refNo), refNo: d.refNo, title: d.title, titleAr: ae ? d.titleAr : undefined, type: d.type, category: d.category, status: d.status, issuedBy: d.issuedBy,
      issuedDate: iso(issuedDate), effectiveDate: d.effective === null ? null : iso(at(d.effective ?? d.issued)!), summary: d.summary, body: d.body ?? '', tags: d.tags, supersedes: d.supersedes ?? '',
      ackRequired: !!d.ackRequired, acknowledgedBy, draftedById: drafter.id, draftedBy: drafter.name,
      approvedById: d.status === 'DRAFT' ? null : approver.id, approvedBy: d.status === 'DRAFT' ? '' : approver.name, approvedAt: d.status === 'DRAFT' ? null : iso(issuedDate.getTime() - rng.int(1, 10) * D), sourceNote: d.sourceNote ?? '',
    };
  }).sort((a, b) => a.issuedDate.localeCompare(b.issuedDate));
}

/* ------------------------------------------------------------------------ the IMO watch --- */

/** One document a monitored IMO source produced, as the legislation desk's watch list holds it. References are marked SIM: they are not IMO document numbers. */
export interface WorldImoWatchItem {
  id: string; source: string; body: string; series: string; reference: string; title: string; subject: string; publishedOn: string; entryIntoForce: string | null; url: string;
  status: 'NEW' | 'ASSESSED' | 'TRANSPOSED' | 'DISMISSED'; assessment: string; assessedById: string | null; assessedBy: string; assessedAt: string | null; dueOn: string | null; instrumentRef: string; firstSeenAt: string;
}
const WATCH_TOPICS: [string, string, string][] = [ // subject, title stem, the national instrument it bears on (a seeded reference, or blank)
  ['Amendments', 'Amendments to the convention chapter on fire protection, adopted at the committee session', ''],
  ['Guidance', 'Guidance on maritime cyber risk management for administrations and companies', 'MSA-CIRC-06/2024'],
  ['Unified interpretation', 'Unified interpretation of the survey and certification provisions for electronic certificates', 'MSA-CIRC-02/2025'],
  ['Amendments', 'Amendments to the ballast water record book form and its entries', 'MSA-CIRC-05/2025'],
  ['Guidance', 'Guidelines on the medical examination of seafarers, revised', 'MSA-CIRC-08/2025'],
  ['Circular', 'Facilitation — electronic submission of the FAL forms through a maritime single window', ''],
  ['Resolution', 'Principles of minimum safe manning, consolidated', ''],
  ['Circular', 'Casualty investigation reporting — revised data set for the global information system', ''],
  ['Amendments', 'Amendments to the training, certification and watchkeeping code — table of competences', ''],
  ['Guidance', 'Interim guidelines on shore power connection for ships in port', 'MSA-CIRC-14/2026'],
];
/** Every monitored source produced a few documents in the last year; the desk has dealt with the older ones and the recent ones wait. */
export function buildImoWatch(rng: Prng, profile: string, lookups: { category: string; code: string; label: string; meta: Record<string, unknown> }[], instruments: WorldLegalInstrument[], users: WorldUser[], now: Date): WorldImoWatchItem[] {
  const sources = lookups.filter((l) => l.category === 'imoSource');
  const legal = usersByRole(users, 'Legal Officer')[0] ?? users[0];
  const refs = new Set(instruments.map((i) => i.refNo));
  const out: WorldImoWatchItem[] = [];
  let n = 0;
  for (const s of sources) {
    const body = String(s.meta.body ?? s.code); const series = String(s.meta.series ?? `${body}/`);
    const count = body === 'GISIS' ? 2 : 3;
    for (let k = 0; k < count; k++) {
      const [subject, stem, bearsOn] = WATCH_TOPICS[(n + k) % WATCH_TOPICS.length];
      const ageDays = 20 + ((n * 37 + k * 61) % 330);
      const published = new Date(now.getTime() - ageDays * D);
      const reference = `${series}SIM-${published.getUTCFullYear()}-${String(10 + n).padStart(2, '0')}`;
      const linked = bearsOn && refs.has(bearsOn) && (profile === 'AE' || !bearsOn.startsWith('MSA-')) ? bearsOn : '';
      const status: WorldImoWatchItem['status'] = ageDays < 45 ? 'NEW' : linked ? 'TRANSPOSED' : ageDays % 3 === 0 ? 'DISMISSED' : 'ASSESSED';
      const assessedAt = status === 'NEW' ? null : iso(published.getTime() + rng.int(3, 20) * D);
      out.push({
        id: stableId('imowatch', `${s.code}:${reference}`), source: s.code, body, series, reference, title: `${stem} (${body})`, subject, publishedOn: iso(published).slice(0, 10),
        entryIntoForce: subject === 'Amendments' ? iso(published.getTime() + 540 * D).slice(0, 10) : null, url: `${String(s.meta.url ?? '')}#${encodeURIComponent(reference)}`,
        status, assessment: status === 'NEW' ? '' : status === 'TRANSPOSED' ? `Transposed by ${linked}.` : status === 'DISMISSED' ? 'No national action needed — already covered by the instruments in force.' : 'Assessed: a national circular is required; drafting scheduled.',
        assessedById: assessedAt ? legal.id : null, assessedBy: assessedAt ? legal.name : '', assessedAt, dueOn: status === 'ASSESSED' ? iso(published.getTime() + 120 * D).slice(0, 10) : null, instrumentRef: linked, firstSeenAt: iso(published.getTime() + D),
      });
      n += 1;
    }
  }
  return out;
}

