/**
 * Renders the gateway route table (services/gateway/src/routes.ts) as nginx `location` blocks to
 * include inside a `server { }` block (for example the web container's nginx or an edge proxy).
 *
 *   pnpm gateway:nginx > infra/nginx/api-locations.conf
 *   pnpm gateway:nginx -- --upstream-host=http://{service}:{port}
 *
 * Upstream URLs come from the same environment variables the Node gateway reads (IDENTITY_URL,
 * MDM_URL, ...); --upstream-host supplies a pattern for every service that has no override.
 * Rate limiting needs one http-level directive, printed in the header comment. No dependencies:
 * runs with Node's type stripping (node --experimental-strip-types tools/gateway/render-nginx.ts).
 */
import { DEFAULT_BODY_LIMIT, ROUTES, SERVICES, UPSTREAM_TIMEOUT_MS, resolveRoutes, type ResolvedRoute } from '../../services/gateway/src/routes.ts';

const args = process.argv.slice(2);
const hostPattern = args.find((a) => a.startsWith('--upstream-host='))?.slice('--upstream-host='.length);
const env: Record<string, string | undefined> = { ...process.env };
if (hostPattern) {
  for (const s of SERVICES) if (!env[s.envKey]) env[s.envKey] = hostPattern.replace('{service}', s.name).replace('{port}', String(s.port));
}
const perMinute = Number(env.RATE_LIMIT_PER_MIN ?? 600);
const perSecond = Math.max(1, Math.ceil(perMinute / 60));
const routes = resolveRoutes(env);
const notFound = JSON.stringify({ success: false, message: 'API route not found' });
const mb = (bytes: number) => `${Math.ceil(bytes / (1024 * 1024))}m`;
const escapeRegex = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');

function block(r: ResolvedRoute): string {
  const lines = [`# ${r.prefix} -> ${r.service}${r.blocked ? ' (blocked at the edge)' : ''}`, `location ~ ^${escapeRegex(r.prefix)}(?:/|$) {`];
  if (r.blocked) {
    lines.push(`  default_type application/json;`, `  return 404 '${notFound}';`, `}`);
    return lines.join('\n');
  }
  lines.push(
    `  limit_req zone=maritime_api burst=${perSecond * 10} nodelay;`,
    `  client_max_body_size ${mb(r.bodyLimit)};`,
    `  rewrite ^${escapeRegex(r.prefix)}(/.*)?$ ${r.rewritePrefix}$1 break;`,
    `  proxy_pass ${r.url};`,
    `  proxy_http_version 1.1;`,
    `  proxy_set_header Host $host;`,
    `  proxy_set_header X-Request-Id $request_id;`,
    `  proxy_set_header X-Correlation-Id $request_id;`,
    `  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;`,
    `  proxy_set_header X-Forwarded-Proto $scheme;`,
    `  proxy_set_header X-Forwarded-Host $host;`,
    `  proxy_set_header X-Service-Token "";`,
    `  proxy_connect_timeout 5s;`,
    `  proxy_read_timeout ${Math.round(UPSTREAM_TIMEOUT_MS / 1000)}s;`,
    `  proxy_send_timeout ${Math.round(UPSTREAM_TIMEOUT_MS / 1000)}s;`,
    `  proxy_intercept_errors off;`,
    `  add_header X-Request-Id $request_id always;`,
    `}`,
  );
  return lines.join('\n');
}

const header = [
  `# Generated by tools/gateway/render-nginx.ts from services/gateway/src/routes.ts — do not edit by hand.`,
  `# Include inside a server { } block. Requires, in the http { } context:`,
  `#   limit_req_zone $binary_remote_addr zone=maritime_api:10m rate=${perSecond}r/s;`,
  `#   limit_req_status 429;`,
  `# Default body limit ${mb(DEFAULT_BODY_LIMIT)}; documents prefixes accept more. Regex locations are matched in file order,`,
  `# so blocks are emitted longest prefix first (${ROUTES.length} prefixes).`,
  ``,
];
const tail = [
  `# Anything else under /api is unknown.`,
  `location /api/ {`,
  `  default_type application/json;`,
  `  return 404 '${notFound}';`,
  `}`,
];
process.stdout.write(`${[...header, ...routes.map(block), '', ...tail].join('\n')}\n`);
