import type { Tier } from './policy';

/* The registry: every tool the AI layer may call, as data. A tool is one named, tiered capability that maps onto
 * one call against a platform service's own API, so the upstream's permission check and scope apply exactly as
 * they do for a person. The registry is seeded into the gateway's `tools` table on start, where an administrator
 * may disable a tool; what is here is the catalogue, what is there is the policy. */

export type Exposure = 'ASSISTANT' | 'AGENT' | 'BOTH';
export type Method = 'GET' | 'POST' | 'PUT';
export interface ArgSpec { type: 'string' | 'number' | 'boolean' | 'list'; description: string; required?: boolean; enum?: string[] }
/** How a tool call becomes an HTTP call: `{name}` in the path is filled from the arguments; the rest go to the query (GET) or the body (POST/PUT), with constants merged in. */
export interface Upstream { service: string; method: Method; path: string; constants?: Record<string, unknown> }
export interface ToolDef {
  name: string; module: string; label: string; labelAr: string; description: string;
  tier: Tier; permission: string; exposure: Exposure; upstream: Upstream; input: Record<string, ArgSpec>; triggers: string[];
}

const q = (description: string, required = false): ArgSpec => ({ type: 'string', description, required });
const n = (description: string, required = false): ArgSpec => ({ type: 'number', description, required });
const ID = { id: q('The record identifier', true) };
const PAGE = { q: q('Free-text search'), limit: n('How many rows, at most (default 20)') };

type Short = [name: string, module: string, label: string, labelAr: string, description: string, permission: string, upstream: Upstream, input: Record<string, ArgSpec>, triggers: string[]];
const read = (...[name, module, label, labelAr, description, permission, upstream, input, triggers]: Short): ToolDef => ({ name, module, label, labelAr, description, tier: 'READ', permission, exposure: 'BOTH', upstream, input, triggers });
const act = (...[name, module, label, labelAr, description, permission, upstream, input, triggers]: Short): ToolDef => ({ name, module, label, labelAr, description, tier: 'ACT', permission, exposure: 'BOTH', upstream, input, triggers });

export const TOOLS: ToolDef[] = [
  /* ---------------------------------------------------------------- Harbour Operations --- */
  read('ops.dashboard', 'ops', 'Harbour dashboard', 'لوحة عمليات الميناء', 'The harbour\'s figures: calls, waiting, turnaround, occupancy, craft utilisation, cargo.', 'portcalls.view', { service: 'ports', method: 'GET', path: '/ops/dashboard' }, {}, ['harbour', 'port operations', 'waiting time', 'turnaround', 'occupancy', 'how busy', 'عمليات الميناء', 'الانتظار', 'الإشغال']),
  read('ops.port_calls', 'ops', 'Port calls', 'زيارات السفن', 'Port calls by status, vessel, berth, agent or date window.', 'portcalls.view', { service: 'ports', method: 'GET', path: '/port-calls' }, { ...PAGE, status: q('EXPECTED, ARRIVED, ALONGSIDE, SAILED…'), vessel: q('Vessel name or IMO'), berth: q('Berth code'), agent: q('Agent code'), from: q('From date (ISO)'), to: q('To date (ISO)'), active: q('true for calls in progress') }, ['port call', 'arrival', 'arrivals', 'departure', 'sailed', 'alongside', 'expected', 'eta', 'due at', 'in port', 'زيارة', 'وصول', 'مغادرة', 'الرسو']),
  read('ops.port_call', 'ops', 'Port call file', 'ملف زيارة السفينة', 'One port call with its services, cargo and timeline.', 'portcalls.view', { service: 'ports', method: 'GET', path: '/port-calls/{id}' }, ID, ['port call file', 'vcn', 'call reference']),
  read('ops.statement_of_facts', 'ops', 'Statement of facts', 'بيان الوقائع', 'The statement of facts for a port call.', 'portcalls.view', { service: 'ports', method: 'GET', path: '/port-calls/{id}/sof' }, ID, ['statement of facts', 'sof', 'laytime', 'بيان الوقائع']),
  read('ops.schedule', 'ops', 'Vessel schedule', 'جدول السفن', 'The arrivals and departures schedule.', 'portcalls.view', { service: 'ports', method: 'GET', path: '/ops/schedule' }, {}, ['schedule', 'timetable', 'next arrivals', 'الجدول', 'المواعيد']),
  read('ops.berth_plan', 'ops', 'Berth plan', 'خطة الأرصفة', 'The berth plan: who is on which berth and when.', 'portcalls.view', { service: 'ports', method: 'GET', path: '/ops/berth-plan' }, {}, ['berth plan', 'berth allocation', 'which berth', 'free berth', 'خطة الأرصفة', 'رصيف']),
  read('ops.berths', 'ops', 'Berths', 'الأرصفة', 'The berths with their status and current occupant.', 'portcalls.view', { service: 'ports', method: 'GET', path: '/berths' }, {}, ['berths', 'berth status', 'quay', 'الأرصفة']),
  read('ops.berth_downtime', 'ops', 'Berth downtime', 'توقف الأرصفة', 'Outages and maintenance windows on the berths.', 'portcalls.view', { service: 'ports', method: 'GET', path: '/berths/downtime' }, {}, ['downtime', 'outage', 'maintenance', 'out of service', 'توقف', 'صيانة']),
  read('ops.craft_utilisation', 'ops', 'Marine craft utilisation', 'استخدام القطع البحرية', 'Pilots, tugs and launches: jobs and utilisation.', 'portcalls.view', { service: 'ports', method: 'GET', path: '/ops/resources/utilisation' }, {}, ['pilot', 'tug', 'launch', 'craft', 'utilisation', 'القطع البحرية', 'المرشد', 'القاطرة']),
  read('ops.twin', 'ops', 'Quay view', 'عرض الرصيف', 'The live quay picture: berths and the vessels on them.', 'portcalls.view', { service: 'ports', method: 'GET', path: '/ops/twin' }, {}, ['quay view', 'twin', 'live picture', 'عرض الرصيف']),
  act('ops.transition_call', 'ops', 'Move a port call', 'تغيير حالة الزيارة', 'Moves a port call to its next state with a note.', 'portcalls.transition', { service: 'ports', method: 'POST', path: '/port-calls/{id}/transition' }, { ...ID, to: q('The state to move to', true), berth: q('Berth code, when berthing'), note: q('Why') }, []),

  /* ------------------------------------------------------------------------------ Ships --- */
  read('ships.dashboard', 'ships', 'Fleet dashboard', 'لوحة الأسطول', 'The fleet: registered tonnage, classes, certificate expiry, risk bands.', 'vessels.view', { service: 'ships', method: 'GET', path: '/vessels/fleet-dashboard' }, {}, ['fleet', 'registered fleet', 'tonnage', 'how many vessels', 'الأسطول', 'الحمولة']),
  read('ships.search', 'ships', 'Vessels', 'السفن', 'Vessels by name, IMO, type, flag, status, agent, class or risk band.', 'vessels.view', { service: 'ships', method: 'GET', path: '/vessels' }, { ...PAGE, type: q('Vessel type'), flag: q('Flag'), status: q('Status'), agent: q('Agent code'), riskBand: q('LOW, MEDIUM, HIGH'), classSociety: q('Class society') }, ['vessel', 'ship', 'imo', 'mmsi', 'call sign', 'flag', 'gross tonnage', 'السفينة', 'سفينة', 'العلم']),
  read('ships.vessel', 'ships', 'Vessel record', 'سجل السفينة', 'One vessel: particulars, ownership, class, certificates, registry.', 'vessels.view', { service: 'ships', method: 'GET', path: '/vessels/{id}' }, ID, ['vessel record', 'particulars', 'owner', 'operator']),
  read('ships.voyages', 'ships', 'Voyages', 'الرحلات', 'A vessel\'s voyages and movements.', 'vessels.view', { service: 'ships', method: 'GET', path: '/vessels/{id}/voyages' }, ID, ['voyage', 'voyages', 'last port', 'next port', 'الرحلة', 'الرحلات']),
  read('ships.certificates', 'ships', 'Ship certificates', 'شهادات السفن', 'Statutory certificates across the fleet, with those expiring soon.', 'certificates.view', { service: 'ships', method: 'GET', path: '/vessels/certificates/all' }, { expiringDays: n('Expiring within this many days') }, ['certificate', 'certificates', 'expiring', 'expiry', 'survey due', 'الشهادات', 'انتهاء']),
  read('ships.dry_dock_due', 'ships', 'Dry dock due', 'استحقاق الحوض الجاف', 'Vessels whose dry docking is due.', 'vessels.view', { service: 'ships', method: 'GET', path: '/vessels/dry-dock-due' }, {}, ['dry dock', 'docking', 'الحوض الجاف']),
  read('ships.risk_targeting', 'ships', 'Risk targeting', 'استهداف المخاطر', 'Vessels ranked by risk score for inspection targeting.', 'risk.view', { service: 'ships', method: 'GET', path: '/risk/targeting' }, {}, ['risk', 'risk score', 'targeting', 'high risk', 'المخاطر']),
  read('ships.registrations', 'ships', 'Registration applications', 'طلبات التسجيل', 'Applications to register, transfer or delete a vessel.', 'registry.view', { service: 'ships', method: 'GET', path: '/registrations' }, { ...PAGE, status: q('Status') }, ['registration', 'register a vessel', 'registry', 'deletion', 'transfer of flag', 'التسجيل', 'السجل']),
  read('ships.registry_dashboard', 'ships', 'Registry dashboard', 'لوحة السجل', 'The registry\'s applications and their ages.', 'registry.view', { service: 'ships', method: 'GET', path: '/registrations/dashboard' }, {}, ['registry dashboard', 'registrations pending']),

  /* ------------------------------------------------------------------------------- Crew --- */
  read('crew.dashboard', 'crew', 'Crew dashboard', 'لوحة البحّارة', 'Seafarers: on board, ashore, certificate alerts, sea service.', 'seafarers.view', { service: 'seafarers', method: 'GET', path: '/seafarers/dashboard' }, {}, ['crew', 'seafarers', 'how many seafarers', 'certificate alerts', 'البحّارة', 'الطاقم']),
  read('crew.search', 'crew', 'Seafarers', 'البحّارة', 'Seafarers by name, rank, nationality, vessel or certificate alert.', 'seafarers.view', { service: 'seafarers', method: 'GET', path: '/seafarers' }, { ...PAGE, rank: q('Rank'), status: q('Status'), nationality: q('Nationality'), vesselId: q('On board this vessel'), certAlerts: q('true for expiring or expired certificates'), onboard: q('true for on board now') }, ['seafarer', 'master', 'chief engineer', 'rank', 'coc', 'stcw', 'seaman', 'بحّار', 'الربان', 'الشهادة']),
  read('crew.seafarer', 'crew', 'Seafarer record', 'سجل البحّار', 'One seafarer: certificates, sea service, sign-ons.', 'seafarers.view', { service: 'seafarers', method: 'GET', path: '/seafarers/{id}' }, ID, ['seafarer record', 'sea service', 'sign on', 'sign off']),
  read('crew.manning', 'crew', 'Manning', 'التطقيم', 'A vessel\'s crew against its safe manning document.', 'seafarers.view', { service: 'seafarers', method: 'GET', path: '/seafarers/manning/{vesselId}' }, { vesselId: q('Vessel identifier', true) }, ['manning', 'safe manning', 'crew on board', 'التطقيم']),
  read('crew.crew_lists', 'crew', 'Crew lists', 'قوائم الطاقم', 'Crew lists lodged for port calls (FAL 5).', 'seafarers.view', { service: 'seafarers', method: 'GET', path: '/seafarers/crew-lists' }, { ...PAGE, status: q('Status') }, ['crew list', 'fal 5', 'fal-5', 'قائمة الطاقم']),
  read('crew.met_dashboard', 'crew', 'MET dashboard', 'لوحة التعليم البحري', 'Maritime education and training: institutions, programmes, accreditation.', 'seafarers.view', { service: 'seafarers', method: 'GET', path: '/seafarers/met/dashboard' }, {}, ['met', 'training institution', 'maritime academy', 'programme', 'التعليم البحري', 'الأكاديمية']),
  act('crew.verify_employment', 'crew', 'Verify employment', 'تحقق من التوظيف', 'Records that a seafarer\'s current employment was verified.', 'seafarers.edit', { service: 'seafarers', method: 'POST', path: '/seafarers/{id}/verify-employment' }, { ...ID, note: q('What was checked') }, []),

  /* ------------------------------------------------------------------------ Legislation --- */
  read('legis.dashboard', 'legis', 'Legislation dashboard', 'لوحة التشريعات', 'Instruments in force, issued this year, due for review, acknowledgements.', 'legislation.view', { service: 'legislation', method: 'GET', path: '/legislation/dashboard' }, {}, ['legislation', 'notices dashboard', 'circulars', 'in force', 'التشريعات', 'التعاميم']),
  read('legis.instruments', 'legis', 'Instruments', 'الصكوك التشريعية', 'Laws, regulations, circulars and notices by type, status, year, subject or tag.', 'legislation.view', { service: 'legislation', method: 'GET', path: '/legislation/instruments' }, { ...PAGE, type: q('LAW, REGULATION, CIRCULAR, NOTICE…'), status: q('DRAFT, IN_FORCE, SUPERSEDED…'), year: q('Year issued'), subject: q('Subject'), tag: q('Tag'), ackRequired: q('true for those needing acknowledgement') }, ['circular', 'notice', 'regulation', 'law', 'decree', 'resolution', 'marine notice', 'requirement', 'تعميم', 'إشعار', 'قانون', 'لائحة', 'قرار']),
  read('legis.instrument', 'legis', 'Instrument', 'صك تشريعي', 'One instrument with its text, versions and acknowledgements.', 'legislation.view', { service: 'legislation', method: 'GET', path: '/legislation/instruments/{id}' }, ID, ['instrument text', 'what does the circular say']),
  read('legis.notices_pending', 'legis', 'Notices awaiting my acknowledgement', 'إشعارات بانتظار الإقرار', 'The notices the reader still has to acknowledge.', 'legislation.view', { service: 'legislation', method: 'GET', path: '/notices/pending' }, {}, ['acknowledge', 'unacknowledged', 'pending notices', 'my notices', 'الإقرار']),
  read('legis.imo_watch', 'legis', 'IMO watch', 'رصد المنظمة البحرية الدولية', 'Items from the IMO sources being monitored, with their status.', 'legislation.view', { service: 'legislation', method: 'GET', path: '/legislation/imo/items' }, { status: q('NEW, ASSESSED, ADOPTED, DISMISSED') }, ['imo', 'msc', 'mepc', 'convention', 'amendment', 'entry into force', 'المنظمة البحرية']),
  act('legis.acknowledge', 'legis', 'Acknowledge a notice', 'الإقرار بإشعار', 'Records the reader\'s acknowledgement of a notice.', 'legislation.view', { service: 'legislation', method: 'POST', path: '/notices/{id}/acknowledge' }, ID, []),

  /* ------------------------------------------------------------- Incidents and traffic --- */
  read('incidents.dashboard', 'incidents', 'Incident dashboard', 'لوحة الحوادث', 'Open incidents, severity mix, response times, closure.', 'incidents.view', { service: 'maritime-centre', method: 'GET', path: '/incidents/dashboard' }, {}, ['incident dashboard', 'how many incidents', 'open incidents', 'الحوادث']),
  read('incidents.list', 'incidents', 'Incidents', 'الحوادث', 'Incidents by category, type, severity, priority, status or source.', 'incidents.view', { service: 'maritime-centre', method: 'GET', path: '/incidents' }, { ...PAGE, category: q('Category'), type: q('Type'), severity: q('Severity'), priority: q('Priority'), status: q('Status') }, ['incident', 'casualty', 'collision', 'grounding', 'pollution', 'oil spill', 'fire', 'man overboard', 'sar', 'distress', 'حادث', 'تصادم', 'جنوح', 'تلوث', 'حريق']),
  read('incidents.incident', 'incidents', 'Incident file', 'ملف الحادث', 'One incident: report, response, communications, tasks, resolution.', 'incidents.view', { service: 'maritime-centre', method: 'GET', path: '/incidents/{id}' }, ID, ['incident file', 'case file']),
  read('incidents.timeline', 'incidents', 'Incident timeline', 'التسلسل الزمني للحادث', 'What happened when on an incident.', 'incidents.view', { service: 'maritime-centre', method: 'GET', path: '/incidents/{id}/timeline' }, ID, ['timeline', 'chronology', 'التسلسل الزمني']),
  act('incidents.add_log', 'incidents', 'Add a log entry', 'إضافة قيد في السجل', 'Adds an entry to an incident\'s log.', 'incidents.manage', { service: 'maritime-centre', method: 'POST', path: '/incidents/{id}/log' }, { ...ID, entry: q('The entry', true) }, []),
  act('incidents.assign', 'incidents', 'Assign an incident', 'إسناد حادث', 'Assigns an incident to a duty officer.', 'incidents.manage', { service: 'maritime-centre', method: 'POST', path: '/incidents/{id}/assign' }, { ...ID, assignedTo: q('The officer\'s name', true), assignedToId: q('The officer\'s user id'), note: q('Why') }, []),
  read('nmc.targets', 'nmc', 'Live targets', 'الأهداف الحية', 'Vessels in the live traffic picture, searched by name, IMO or MMSI.', 'nmc.view', { service: 'maritime-centre', method: 'GET', path: '/tracking/targets/search' }, { q: q('Name, IMO or MMSI', true) }, ['where is', 'position', 'live traffic', 'ais', 'track', 'speed', 'course', 'أين', 'الموقع', 'الحركة الملاحية']),
  read('nmc.alerts', 'nmc', 'Traffic alerts', 'تنبيهات الحركة', 'Geofence, anchorage-overstay and restricted-area alerts.', 'nmc.view', { service: 'maritime-centre', method: 'GET', path: '/tracking/alerts' }, {}, ['alert', 'alerts', 'geofence', 'restricted area', 'overstay', 'تنبيه', 'منطقة محظورة']),
  read('nmc.restrictions', 'nmc', 'Navigational restrictions', 'القيود الملاحية', 'Restricted areas and navigational warnings in force.', 'nmc.view', { service: 'maritime-centre', method: 'GET', path: '/tracking/restrictions' }, {}, ['restriction', 'navigational warning', 'notice to mariners', 'closed area', 'القيود الملاحية']),

  /* --------------------------------------------------------------------------- Inspection --- */
  read('inspect.dashboard', 'inspect', 'Inspection dashboard', 'لوحة التفتيش', 'Inspections, deficiencies, detentions and the six 18-month KPIs.', 'inspections.view', { service: 'inspection', method: 'GET', path: '/inspections/dashboard' }, {}, ['inspection dashboard', 'psc', 'port state control', 'flag state inspection', 'التفتيش', 'رقابة دولة الميناء']),
  read('inspect.list', 'inspect', 'Inspections', 'عمليات التفتيش', 'Inspections by type, regime, status, result, vessel, inspector or detention.', 'inspections.view', { service: 'inspection', method: 'GET', path: '/inspections' }, { ...PAGE, type: q('Type'), regime: q('Regime'), status: q('Status'), result: q('Result'), vessel: q('Vessel name or IMO'), detention: q('true for detentions') }, ['inspection', 'inspected', 'inspector', 'survey', 'audit', 'تفتيش', 'مفتش', 'معاينة']),
  read('inspect.inspection', 'inspect', 'Inspection file', 'ملف التفتيش', 'One inspection: checklist, findings, deficiencies, report.', 'inspections.view', { service: 'inspection', method: 'GET', path: '/inspections/{id}' }, ID, ['inspection file', 'inspection report']),
  read('inspect.deficiencies', 'inspect', 'Deficiencies', 'أوجه القصور', 'Deficiencies recorded, by code and status.', 'inspections.view', { service: 'inspection', method: 'GET', path: '/inspections/deficiencies' }, PAGE, ['deficiency', 'deficiencies', 'non-conformity', 'finding', 'أوجه القصور', 'ملاحظة']),
  read('inspect.detentions', 'inspect', 'Detentions', 'الاحتجازات', 'Vessels detained and released.', 'inspections.view', { service: 'inspection', method: 'GET', path: '/inspections/detentions' }, PAGE, ['detention', 'detained', 'release', 'الاحتجاز', 'محتجزة']),
  read('inspect.kpis', 'inspect', 'Inspection KPIs', 'مؤشرات التفتيش', 'The instrumented inspection KPIs over eighteen months.', 'inspections.view', { service: 'inspection', method: 'GET', path: '/inspections/kpis' }, {}, ['inspection kpi', 'detention rate', 'deficiency rate', 'inspection rate', 'مؤشرات']),
  read('inspect.recommendations', 'inspect', 'Recommendations', 'التوصيات', 'Recommendations raised by inspections and their decisions.', 'inspections.view', { service: 'inspection', method: 'GET', path: '/inspections/recommendations' }, PAGE, ['recommendation', 'recommendations', 'التوصيات']),

  /* ------------------------------------------------------------ Facilities and companies --- */
  read('facil.dashboard', 'facil', 'Companies dashboard', 'لوحة الشركات', 'Licensed companies, expiries, renewals, applications, obligations, ratings.', 'facilities.view', { service: 'facilities', method: 'GET', path: '/facilities/dashboard' }, {}, ['companies dashboard', 'licensed companies', 'how many companies', 'الشركات المرخصة']),
  read('facil.companies', 'facil', 'Companies', 'الشركات', 'Port companies by category, type, status, rating or city.', 'facilities.view', { service: 'facilities', method: 'GET', path: '/facilities/companies' }, { ...PAGE, category: q('Category'), type: q('Type'), status: q('Status'), rating: q('Rating band'), city: q('City') }, ['company', 'agent', 'shipping agent', 'stevedore', 'bunker', 'chandler', 'operator', 'licensee', 'شركة', 'وكيل', 'الوكيل الملاحي']),
  read('facil.company', 'facil', 'Company record', 'سجل الشركة', 'One company: licence, accreditation, obligations, audits, rating.', 'facilities.view', { service: 'facilities', method: 'GET', path: '/facilities/companies/{id}' }, ID, ['company record', 'company file']),
  read('facil.renewals', 'facil', 'Renewals due', 'التجديدات المستحقة', 'Licences due for renewal.', 'facilities.view', { service: 'facilities', method: 'GET', path: '/facilities/renewals' }, {}, ['renewal', 'renewals', 'renew', 'expiring licence', 'التجديد']),
  read('facil.obligations', 'facil', 'Obligations', 'الالتزامات', 'Open and overdue obligations on companies and facilities.', 'facilities.view', { service: 'facilities', method: 'GET', path: '/facilities/obligations' }, {}, ['obligation', 'obligations', 'overdue obligation', 'condition', 'الالتزامات']),
  read('facil.accreditations', 'facil', 'Accreditations', 'الاعتمادات', 'Annual accreditations by scheme and status.', 'facilities.view', { service: 'facilities', method: 'GET', path: '/facilities/accreditations' }, { ...PAGE, status: q('Status') }, ['accreditation', 'accredited', 'scheme', 'الاعتماد']),
  read('facil.port_facilities', 'facil', 'Port facilities', 'المرافق المينائية', 'Port facilities with their ISPS and security-review state.', 'facilities.view', { service: 'facilities', method: 'GET', path: '/facilities/port-facilities' }, PAGE, ['port facility', 'terminal', 'isps', 'security review', 'pfso', 'المرافق المينائية', 'الأمن']),
  read('facil.licences_expiring', 'facil', 'Instruments expiring', 'الصكوك المنتهية قريباً', 'Licences, permits and certificates expiring within a window.', 'facilities.view', { service: 'instruments', method: 'GET', path: '/instruments/expiring' }, { days: n('Within this many days') }, ['licence expiring', 'permit expiring', 'expiring soon', 'about to expire', 'ينتهي قريباً']),
  read('facil.licences', 'facil', 'Licences and permits', 'التراخيص والتصاريح', 'Licences, permits and certificates by class, status or subject.', 'facilities.view', { service: 'instruments', method: 'GET', path: '/licenses' }, { ...PAGE, status: q('Status'), subjectKind: q('COMPANY, VESSEL, SEAFARER, FACILITY'), instrumentClass: q('Class'), expiringDays: n('Expiring within this many days') }, ['licence', 'license', 'permit', 'noc', 'authorisation', 'ترخيص', 'تصريح']),

  /* ------------------------------------------------------------------------ Service Desk --- */
  read('services.dashboard', 'services', 'Service Desk dashboard', 'لوحة مكتب الخدمات', 'Applications received and decided, service-level attainment, fees.', 'services.view', { service: 'workflow', method: 'GET', path: '/services/dashboard' }, {}, ['service desk', 'applications dashboard', 'sla', 'service level', 'backlog', 'مكتب الخدمات', 'الطلبات']),
  read('services.catalogue', 'services', 'Service catalogue', 'دليل الخدمات', 'The services citizens and companies may apply for.', 'services.view', { service: 'workflow', method: 'GET', path: '/services/catalogue' }, { q: q('Free-text search') }, ['catalogue', 'which services', 'how to apply', 'apply for', 'requirements for', 'fee for', 'دليل الخدمات', 'كيف أتقدم', 'الرسوم']),
  read('services.applications', 'services', 'Applications', 'الطلبات', 'Applications by status, scope (open, breached, mine) or definition.', 'services.view', { service: 'workflow', method: 'GET', path: '/services/requests' }, { ...PAGE, status: q('Status'), scope: q('open, breached or mine'), definition: q('Service key') }, ['application', 'applications', 'request', 'pending applications', 'breached', 'overdue applications', 'طلب', 'الطلبات المتأخرة']),
  read('services.application', 'services', 'Application file', 'ملف الطلب', 'One application: form, documents, checks, timeline, fees.', 'services.view', { service: 'workflow', method: 'GET', path: '/services/requests/{id}' }, ID, ['application file', 'application status']),
  act('services.add_note', 'services', 'Add a note', 'إضافة ملاحظة', 'Adds a note to an application\'s file.', 'services.view', { service: 'workflow', method: 'POST', path: '/services/requests/{id}/notes' }, { ...ID, body: q('The note', true), internal: { type: 'boolean', description: 'true keeps it off the applicant\'s view' } }, []),
  act('services.request_info', 'services', 'Request information', 'طلب معلومات', 'Asks the applicant for more information, with the reason.', 'services.assess', { service: 'workflow', method: 'POST', path: '/services/requests/{id}/transition', constants: { action: 'request_info' } }, { ...ID, note: q('What is needed', true) }, []),
  act('services.assign', 'services', 'Assign an application', 'إسناد طلب', 'Assigns an application to an assessor.', 'services.assess', { service: 'workflow', method: 'POST', path: '/services/requests/{id}/assign' }, { ...ID, userId: q('The assessor\'s user id', true), name: q('The assessor\'s name') }, []),
  act('services.verify_document', 'services', 'Verify a document', 'التحقق من مستند', 'Marks a lodged document as verified or rejected.', 'services.assess', { service: 'workflow', method: 'PUT', path: '/services/requests/{id}/documents/{code}' }, { ...ID, code: q('Document code', true), verified: { type: 'boolean', description: 'true when it passes', required: true }, notes: q('Finding') }, []),

  /* ---------------------------------------------------------------------------- Billing --- */
  read('finance.dashboard', 'finance', 'Receivables dashboard', 'لوحة الذمم المدينة', 'Billed, collected, outstanding, ageing, DSO, collection effectiveness.', 'invoices.view', { service: 'revenue', method: 'GET', path: '/invoices/dashboard' }, {}, ['receivables', 'billing dashboard', 'revenue', 'collected', 'outstanding', 'ageing', 'dso', 'الإيرادات', 'الذمم', 'المتأخرات']),
  read('finance.invoices', 'finance', 'Invoices', 'الفواتير', 'Invoices by status, vessel, port call, date window or overdue.', 'invoices.view', { service: 'revenue', method: 'GET', path: '/invoices' }, { ...PAGE, status: q('DRAFT, ISSUED, PAID, OVERDUE, CANCELLED'), vessel: q('Vessel name or IMO'), vcn: q('Port call reference'), from: q('From date'), to: q('To date'), overdue: q('true for overdue') }, ['invoice', 'invoices', 'bill', 'billed', 'unpaid', 'overdue', 'due', 'فاتورة', 'الفواتير', 'مستحق']),
  read('finance.invoice', 'finance', 'Invoice', 'فاتورة', 'One invoice with its lines, payments and reminders.', 'invoices.view', { service: 'revenue', method: 'GET', path: '/invoices/{id}' }, ID, ['invoice number', 'invoice detail']),
  read('finance.summary', 'finance', 'Billing summary', 'ملخص الفوترة', 'Totals by status and period.', 'invoices.view', { service: 'revenue', method: 'GET', path: '/invoices/summary' }, {}, ['billing summary', 'total billed', 'total collected']),
  read('finance.tariffs', 'finance', 'Tariffs', 'التعرفة', 'The tariff book: dues and charges in force.', 'invoices.view', { service: 'revenue', method: 'GET', path: '/tariffs' }, {}, ['tariff', 'tariffs', 'dues', 'charge', 'rate', 'how much does', 'التعرفة', 'الرسوم']),
  act('finance.send_reminder', 'finance', 'Send a payment reminder', 'إرسال تذكير بالسداد', 'Sends the debtor a reminder for an overdue invoice and records it.', 'invoices.issue', { service: 'revenue', method: 'POST', path: '/invoices/{id}/remind' }, { ...ID, note: q('Anything to add') }, []),

  /* ------------------------------------------------------------------------- MIS and data --- */
  read('mis.dashboard', 'mis', 'Command Centre', 'مركز القيادة', 'The platform-wide picture.', 'dashboard.view', { service: 'reporting', method: 'GET', path: '/dashboard' }, {}, ['command centre', 'overview', 'headline', 'big picture', 'مركز القيادة', 'نظرة عامة']),
  read('mis.module_strip', 'mis', 'Module headlines', 'عناوين الوحدات', 'Three headline figures for every module.', 'dashboard.view', { service: 'reporting', method: 'GET', path: '/dashboard/modules' }, {}, ['every module', 'all modules', 'headline figures']),
  read('mis.catalogue', 'mis', 'Report catalogue', 'دليل التقارير', 'The reports available to run.', 'reports.view', { service: 'reporting', method: 'GET', path: '/reports/catalog' }, {}, ['report', 'reports', 'which reports', 'التقارير']),
  read('mis.report', 'mis', 'Run a report', 'تشغيل تقرير', 'Runs a catalogued report and returns its rows.', 'reports.view', { service: 'reporting', method: 'GET', path: '/reports/run/{key}' }, { key: q('Report key', true) }, ['run report', 'report on', 'تقرير']),
  read('mis.mis', 'mis', 'MIS report', 'تقرير نظم المعلومات', 'The monthly management information report.', 'reports.view', { service: 'reporting', method: 'GET', path: '/reports/mis' }, {}, ['mis', 'management information', 'monthly report', 'التقرير الشهري']),
  read('mis.search', 'mis', 'Search everything', 'البحث الشامل', 'Searches every register at once.', 'dashboard.view', { service: 'reporting', method: 'GET', path: '/search' }, { q: q('What to look for', true) }, ['find', 'search', 'look up', 'ابحث', 'أين أجد']),
  read('masters.dashboard', 'masters', 'Data Studio dashboard', 'لوحة استوديو البيانات', 'Data quality: completeness, bilingual coverage, duplicates, validity, timeliness.', 'masters.view', { service: 'mdm', method: 'GET', path: '/golden/dashboard' }, {}, ['data quality', 'master data', 'duplicates', 'completeness', 'golden record', 'جودة البيانات', 'البيانات الرئيسية']),
  read('masters.lookups', 'masters', 'Reference data', 'البيانات المرجعية', 'Reference lists by category.', 'masters.view', { service: 'mdm', method: 'GET', path: '/lookups' }, { ...PAGE, category: q('Category'), active: q('true or false') }, ['lookup', 'reference list', 'code list', 'master list', 'القوائم المرجعية']),
  read('masters.golden_vessels', 'masters', 'Golden vessels', 'السجل الذهبي للسفن', 'The golden vessel records shared across modules.', 'vessels.view', { service: 'mdm', method: 'GET', path: '/golden/vessels' }, PAGE, ['golden vessel', 'vessel master']),
  read('masters.golden_companies', 'masters', 'Golden companies', 'السجل الذهبي للشركات', 'The golden company records shared across modules.', 'facilities.view', { service: 'mdm', method: 'GET', path: '/companies' }, PAGE, ['golden company', 'company master']),

  /* ----------------------------------------------------------------------- Administration --- */
  read('admin.dashboard', 'admin', 'Access posture', 'وضع الوصول', 'Accounts, second-factor coverage, dormant and privileged accounts, sessions, the four-eyes queue.', 'users.view', { service: 'identity-access', method: 'GET', path: '/users/dashboard' }, {}, ['users dashboard', 'access posture', 'mfa coverage', 'dormant accounts', 'privileged', 'sessions', 'الحسابات', 'الوصول']),
  read('admin.users', 'admin', 'Users', 'المستخدمون', 'Accounts by role, department, activity, dormancy or second-factor state.', 'users.view', { service: 'identity-access', method: 'GET', path: '/users' }, { ...PAGE, role: q('Role name'), department: q('Department'), active: q('true or false'), dormant: q('true for dormant'), mfa: q('enrolled or missing') }, ['user', 'users', 'account', 'accounts', 'who has', 'role of', 'مستخدم', 'حساب', 'الدور']),
  read('admin.changes', 'admin', 'Pending approvals', 'الموافقات المعلقة', 'Privileged changes awaiting a second person.', 'users.view', { service: 'identity-access', method: 'GET', path: '/users/changes' }, { status: q('PENDING, APPROVED, REJECTED') }, ['approval', 'approvals', 'four eyes', 'pending change', 'الموافقات']),
  read('admin.reviews', 'admin', 'Access reviews', 'مراجعات الوصول', 'Access review cycles and their state.', 'users.view', { service: 'identity-access', method: 'GET', path: '/access-reviews' }, {}, ['access review', 'attestation', 'مراجعة الوصول']),
  read('admin.audit', 'admin', 'Audit summary', 'ملخص التدقيق', 'Audit events by day, action, service and actor.', 'audit.view', { service: 'audit-ledger', method: 'GET', path: '/audit/summary' }, {}, ['audit', 'audit trail', 'who changed', 'who did', 'سجل التدقيق']),

  /* ----------------------------------------------------------------------------- Platform --- */
  read('platform.status', 'platform', 'Platform status', 'حالة المنصة', 'Services up, targets, open platform incidents.', 'platform.view', { service: 'observability', method: 'GET', path: '/platform/status' }, {}, ['platform status', 'services up', 'is the platform', 'health', 'uptime', 'حالة المنصة']),
  read('platform.slas', 'platform', 'Platform SLAs', 'اتفاقيات مستوى الخدمة', 'Availability against the committed levels.', 'platform.view', { service: 'observability', method: 'GET', path: '/platform/slas' }, {}, ['sla', 'availability', 'downtime', 'التوافر']),
  read('platform.jobs', 'platform', 'Scheduled jobs', 'المهام المجدولة', 'The scheduler\'s jobs and their last runs.', 'settings.view', { service: 'scheduler', method: 'GET', path: '/jobs' }, {}, ['job', 'jobs', 'scheduled', 'sweep', 'cron', 'المهام المجدولة']),
  read('platform.deliveries', 'platform', 'Notification deliveries', 'تسليم الإشعارات', 'Notifications sent, delivered and failed.', 'platform.view', { service: 'notifications', method: 'GET', path: '/notifications/deliveries' }, {}, ['delivery', 'deliveries', 'email sent', 'sms sent', 'notification failed']),
  read('docs.extract', 'platform', 'Read a document', 'قراءة مستند', 'Reads the fields asked for out of a lodged document through the in-country model platform.', 'ai.use', { service: 'ai-platform', method: 'POST', path: '/ai-platform/vision/extract' }, { documentRef: q('The document reference', true), fields: { type: 'list', description: 'The fields to read, comma-separated', required: true }, subject: q('What the document is about'), pages: n('How many pages') }, ['extract', 'read the document', 'what does the document say', 'استخراج', 'اقرأ المستند']),
  read('docs.search', 'platform', 'Documents', 'المستندات', 'Documents by the record they belong to or their type.', 'dashboard.view', { service: 'documents', method: 'GET', path: '/documents' }, { ...PAGE, entityType: q('Record type'), entityId: q('Record identifier'), docType: q('Document type') }, ['document', 'documents', 'attachment', 'uploaded', 'file', 'المستندات', 'المرفقات']),
];

export const toolByName = (name: string) => TOOLS.find((t) => t.name === name) ?? null;
export const MODULE_KEYS = [...new Set(TOOLS.map((t) => t.module))];
