import { Controller, Get } from '@nestjs/common';
import * as C from '@maritime/contracts';

/** Everything the web client needs to render matrices, chips and forms without hard-coding enums. */
@Controller('meta')
export class MetaController {
  @Get()
  meta() {
    return {
      permissionGroups: [...C.PERMISSION_GROUPS, ...C.EXTENDED_PERMISSION_GROUPS],
      lookupCategories: C.LOOKUP_CATEGORIES,
      enums: {
        PORTCALL_STATUS: C.PORTCALL_STATUS, INSPECTION_TYPES: C.INSPECTION_TYPES, INSPECTION_STATUS: C.INSPECTION_STATUS, INSPECTION_RESULTS: C.INSPECTION_RESULTS,
        INVOICE_STATUS: C.INVOICE_STATUS, INSTRUMENT_TYPES: C.INSTRUMENT_TYPES, INSTRUMENT_STATUS: C.INSTRUMENT_STATUS, LICENSE_STATUS: C.LICENSE_STATUS,
        REQUEST_STATUS: C.REQUEST_STATUS, REGISTRATION_KINDS: C.REGISTRATION_KINDS, REGISTRATION_STATUS: C.REGISTRATION_STATUS, REGISTRY_STATES: C.REGISTRY_STATES,
        INCIDENT_CATEGORIES: C.INCIDENT_CATEGORIES, INCIDENT_TYPES: C.INCIDENT_TYPES, INCIDENT_STATUS: C.INCIDENT_STATUS, INCIDENT_SEVERITY: C.INCIDENT_SEVERITY, INCIDENT_PRIORITIES: C.INCIDENT_PRIORITIES, INCIDENT_SOURCES: C.INCIDENT_SOURCES,
        SUBJECT_KINDS: C.SUBJECT_KINDS, INSTRUMENT_CLASSES: C.INSTRUMENT_CLASSES, LICENSE_TYPES: C.LICENSE_TYPES, SEAFARER_RANKS: C.SEAFARER_RANKS, SEAFARER_CERT_TYPES: C.SEAFARER_CERT_TYPES, RESOURCE_TYPES: C.RESOURCE_TYPES,
        ENDORSEMENT_KINDS: C.ENDORSEMENT_KINDS, ENDORSEMENT_RESULTS: C.ENDORSEMENT_RESULTS, DELETION_REASONS: C.DELETION_REASONS, AMENDMENT_TYPES: C.AMENDMENT_TYPES,
      },
      licenseTypesBySubject: C.LICENSE_TYPES_BY_SUBJECT,
      moduleSettingDefaults: C.MODULE_SETTING_DEFAULTS,
      jurisdictions: Object.values(C.JURISDICTIONS).map((j) => ({ code: j.code, name: j.name, currency: j.currency, tax: j.tax, languages: j.languages })),
      languages: C.SUPPORTED_LANGUAGES,
    };
  }
}
