/* Insights: what each module's own figures say a person should look at next, and — where a tool exists for it —
 * the action that answers it, run through the tool gateway as that person. Every rule is a pure function of the
 * dashboard payload the module already computes, so an insight is only ever as true as the dashboard it reads. */

type Row = Record<string, any>;
export type Severity = 'info' | 'warning' | 'critical';
export interface InsightAction { tool: string; args: Record<string, unknown>; label: string; labelAr: string; tier: 'READ' | 'ACT' }
export interface Insight {
  id: string; module: string; severity: Severity; title: string; titleAr: string; detail: string; detailAr: string;
  metric?: { label: string; value: number | string; target?: number | string; format?: 'count' | 'money' | 'hours' | 'pct' | 'days' };
  link?: string; action?: InsightAction;
}
/** The gateway tool that carries each module's dashboard. */
export const MODULE_DASHBOARD: Record<string, string> = {
  ops: 'ops.dashboard', ships: 'ships.dashboard', crew: 'crew.dashboard', legis: 'legis.dashboard', incidents: 'incidents.dashboard', inspect: 'inspect.dashboard',
  facil: 'facil.dashboard', services: 'services.dashboard', finance: 'finance.dashboard', mis: 'mis.dashboard', masters: 'masters.dashboard', admin: 'admin.dashboard', platform: 'platform.status',
};
export const INSIGHT_MODULES = Object.keys(MODULE_DASHBOARD);

const n = (v: unknown, d = 0) => (v == null || v === '' || Number.isNaN(Number(v)) ? d : Number(v));
const pct = (v: unknown) => `${Math.round(n(v))}%`;
const money = (v: unknown, cur = 'AED') => `${cur} ${Math.round(n(v)).toLocaleString('en-AE')}`;
const mk = (module: string, id: string, severity: Severity, title: string, titleAr: string, detail: string, detailAr: string, rest: Partial<Insight> = {}): Insight => ({ id: `${module}.${id}`, module, severity, title, titleAr, detail, detailAr, ...rest });

export function insightsFor(module: string, data: Row, now = new Date()): Insight[] {
  const k: Row = data?.kpis ?? {};
  const t: Row = data?.targets ?? {};
  const out: Insight[] = [];
  switch (module) {
    case 'ops': {
      if (n(k.berthOccupancyPct) >= n(t.congestionPct, 85)) out.push(mk(module, 'congested', 'critical', 'The berths are congested', 'الأرصفة مزدحمة', `Occupancy is ${pct(k.berthOccupancyPct)} against a congestion line of ${pct(t.congestionPct ?? 85)}; ${n(k.expected72h)} arrivals are expected within 72 hours. Review the berth plan before they anchor.`, `الإشغال ${pct(k.berthOccupancyPct)} مقابل حد الازدحام ${pct(t.congestionPct ?? 85)}؛ ${n(k.expected72h)} وصول متوقع خلال 72 ساعة. راجع خطة الأرصفة قبل أن ترسو.`, { metric: { label: 'Occupancy', value: n(k.berthOccupancyPct), target: n(t.congestionPct, 85), format: 'pct' }, link: '/ops/berth-plan', action: { tool: 'ops.berth_plan', args: {}, label: 'Open the berth plan', labelAr: 'افتح خطة الأرصفة', tier: 'READ' } }));
      if (n(k.waitingOverAlertPct) > 0) out.push(mk(module, 'anchorage-overstay', 'warning', 'Calls waited beyond the anchorage alert', 'زيارات انتظرت أكثر من حد التنبيه', `${pct(k.waitingOverAlertPct)} of the calls in the last 30 days waited past ${n(t.anchorageAlertHrs, 24)} h at anchorage; ${n(k.atAnchorage)} vessel(s) are at anchorage now.`, `${pct(k.waitingOverAlertPct)} من الزيارات خلال 30 يوماً انتظرت أكثر من ${n(t.anchorageAlertHrs, 24)} ساعة؛ ${n(k.atAnchorage)} سفينة في المرسى الآن.`, { metric: { label: 'Over the alert', value: n(k.waitingOverAlertPct), target: 0, format: 'pct' }, link: '/ops/overview' }));
      if (n(k.avgWaitingHrs) > n(t.waitingHrs, 4)) out.push(mk(module, 'waiting', 'warning', 'Average waiting time is above target', 'متوسط زمن الانتظار أعلى من الهدف', `Vessels waited ${n(k.avgWaitingHrs).toFixed(1)} h on average against a target of ${n(t.waitingHrs, 4)} h; only ${pct(k.waitingWithinTargetPct)} were within it.`, `انتظرت السفن ${n(k.avgWaitingHrs).toFixed(1)} ساعة في المتوسط مقابل هدف ${n(t.waitingHrs, 4)} ساعات؛ ${pct(k.waitingWithinTargetPct)} فقط ضمن الهدف.`, { metric: { label: 'Avg waiting', value: n(k.avgWaitingHrs), target: n(t.waitingHrs, 4), format: 'hours' }, link: '/ops/overview' }));
      if (n(k.etaReliabilityPct, 100) < 80) out.push(mk(module, 'eta', 'info', 'Arrival estimates are unreliable', 'تقديرات الوصول غير موثوقة', `Only ${pct(k.etaReliabilityPct)} of arrivals came within ${n(t.etaSlackHrs, 4)} h of their declared time; the berth plan is planning on poor information.`, `${pct(k.etaReliabilityPct)} فقط من الوصول جاء ضمن ${n(t.etaSlackHrs, 4)} ساعات من الوقت المعلن.`, { metric: { label: 'ETA reliability', value: n(k.etaReliabilityPct), target: 80, format: 'pct' }, link: '/ops/schedule' }));
      if (n(k.berthsUnderMaintenance) > 0) out.push(mk(module, 'maintenance', 'info', 'Berths out of service', 'أرصفة خارج الخدمة', `${n(k.berthsUnderMaintenance)} berth(s) are under maintenance; ${n(k.berthDowntimeHrs30d).toFixed(0)} h of downtime in 30 days.`, `${n(k.berthsUnderMaintenance)} رصيف تحت الصيانة؛ ${n(k.berthDowntimeHrs30d).toFixed(0)} ساعة توقف خلال 30 يوماً.`, { link: '/ops/berths', action: { tool: 'ops.berth_downtime', args: {}, label: 'See the outages', labelAr: 'اعرض الأعطال', tier: 'READ' } }));
      break;
    }
    case 'ships': {
      const certs: Row = data?.certs ?? {}; const alerts: Row[] = Array.isArray(data?.certAlertVessels) ? data.certAlertVessels : [];
      const expired = n(certs.expired ?? certs.EXPIRED); const expiring = n(certs.expiring ?? certs.EXPIRING);
      if (expired > 0) out.push(mk(module, 'expired', 'critical', 'Statutory certificates have lapsed', 'شهادات قانونية انتهت', `${expired} certificate(s) on the register are expired${alerts.length ? `, on ${alerts.length} vessel(s)` : ''}. A vessel trading on a lapsed certificate is a detention waiting to happen.`, `${expired} شهادة على السجل منتهية${alerts.length ? ` على ${alerts.length} سفينة` : ''}.`, { metric: { label: 'Expired', value: expired, target: 0 }, link: '/vessels/certificates', action: { tool: 'ships.certificates', args: { expiringDays: 0 }, label: 'List the lapsed certificates', labelAr: 'اعرض الشهادات المنتهية', tier: 'READ' } }));
      if (expiring > 0) out.push(mk(module, 'expiring', 'warning', 'Certificates expire within the window', 'شهادات تنتهي قريباً', `${expiring} certificate(s) expire within the alert window; renewals take weeks, so the surveys need booking now.`, `${expiring} شهادة تنتهي ضمن نافذة التنبيه؛ التجديد يستغرق أسابيع.`, { metric: { label: 'Expiring', value: expiring }, link: '/vessels/certificates' }));
      if (n(k.atAnchor) > 0 && n(k.inPort) > 0 && n(k.atAnchor) / Math.max(1, n(k.inPort)) > 0.5) out.push(mk(module, 'anchor', 'info', 'A large share of the fleet is at anchor', 'حصة كبيرة من الأسطول في المرسى', `${n(k.atAnchor)} of the fleet's vessels are at anchor against ${n(k.inPort)} in port.`, `${n(k.atAnchor)} سفينة في المرسى مقابل ${n(k.inPort)} في الميناء.`, { link: '/traffic' }));
      break;
    }
    case 'crew': {
      const alerts: Row[] = Array.isArray(data?.alertList) ? data.alertList : [];
      if (n(k.medicalIssues) > 0) out.push(mk(module, 'medical', 'warning', 'Seafarers with a medical certificate issue', 'بحّارة لديهم مشكلة في الشهادة الطبية', `${n(k.medicalIssues)} seafarer(s) have a medical certificate expired or expiring within ${n(k.medicalWindow, 45)} days; they cannot sign on until it is renewed.`, `${n(k.medicalIssues)} بحّاراً لديهم شهادة طبية منتهية أو تنتهي خلال ${n(k.medicalWindow, 45)} يوماً.`, { metric: { label: 'Medical issues', value: n(k.medicalIssues), target: 0 }, link: '/seafarers', action: { tool: 'crew.search', args: { certAlerts: 'true', limit: 20 }, label: 'List the seafarers concerned', labelAr: 'اعرض البحّارة المعنيين', tier: 'READ' } }));
      if (alerts.length) out.push(mk(module, 'documents', 'warning', 'Crew documents need attention', 'مستندات الطاقم تحتاج إلى متابعة', `${alerts.length} document alert(s) are open across the roll — certificates of competency, endorsements and medicals nearing expiry.`, `${alerts.length} تنبيه مستندات مفتوح عبر القوائم.`, { metric: { label: 'Document alerts', value: alerts.length }, link: '/seafarers/overview' }));
      if (n(k.roll) && n(k.onboard) / n(k.roll) < 0.4) out.push(mk(module, 'ashore', 'info', 'Most of the roll is ashore', 'معظم القائمة على اليابسة', `${n(k.ashore)} of ${n(k.roll)} seafarers are ashore; manning for the expected calls may draw on them.`, `${n(k.ashore)} من ${n(k.roll)} بحّاراً على اليابسة.`, { link: '/seafarers/overview' }));
      break;
    }
    case 'legis': {
      const cur: Row = data?.currency ?? {};
      if (n(k.ackOutstanding) > 0) out.push(mk(module, 'acks', 'warning', 'Acknowledgements are outstanding', 'إقرارات معلقة', `${n(k.ackOutstanding)} acknowledgement(s) are outstanding on ${n(k.ackRequired)} instrument(s); compliance stands at ${pct(k.ackCompliancePct)}.`, `${n(k.ackOutstanding)} إقراراً معلقاً على ${n(k.ackRequired)} صكاً؛ الامتثال ${pct(k.ackCompliancePct)}.`, { metric: { label: 'Acknowledgement compliance', value: n(k.ackCompliancePct), target: 90, format: 'pct' }, link: '/legislation/overview', action: { tool: 'legis.notices_pending', args: {}, label: 'Show what I still have to acknowledge', labelAr: 'اعرض ما عليّ الإقرار به', tier: 'READ' } }));
      if (n(k.awaitingReview) + n(k.awaitingApproval) > 0) out.push(mk(module, 'drafts', 'info', 'Drafts await a decision', 'مسودات بانتظار قرار', `${n(k.awaitingReview)} draft(s) await review and ${n(k.awaitingApproval)} await approval.`, `${n(k.awaitingReview)} مسودة بانتظار المراجعة و${n(k.awaitingApproval)} بانتظار الاعتماد.`, { link: '/legislation?status=DRAFT' }));
      if (n(cur.olderThanReview) > 0) out.push(mk(module, 'review', 'info', 'Instruments are past their review age', 'صكوك تجاوزت عمر المراجعة', `${n(cur.olderThanReview)} instrument(s) in force are older than the ${n(cur.reviewYears, 5)}-year review cycle (${pct(cur.olderThanReviewPct)} of those in force).`, `${n(cur.olderThanReview)} صكاً سارياً تجاوز دورة المراجعة البالغة ${n(cur.reviewYears, 5)} سنوات.`, { metric: { label: 'Past review age', value: n(cur.olderThanReview) }, link: '/legislation/overview' }));
      if (n(k.lapsingSoon) > 0) out.push(mk(module, 'lapsing', 'warning', 'Instruments lapse soon', 'صكوك تنتهي قريباً', `${n(k.lapsingSoon)} instrument(s) lapse within the window; decide whether to renew, replace or let them go.`, `${n(k.lapsingSoon)} صكاً ينتهي قريباً.`, { link: '/legislation' }));
      break;
    }
    case 'incidents': {
      if (n(k.highOpen) > 0) out.push(mk(module, 'high', 'critical', 'High or critical incidents are open', 'حوادث عالية أو حرجة مفتوحة', `${n(k.highOpen)} of the ${n(k.open)} open incident(s) are high or critical. Mean time to acknowledge is ${n(k.mttaMin)} min and to resolve ${n(k.mttrHrs).toFixed(1)} h.`, `${n(k.highOpen)} من ${n(k.open)} حادثاً مفتوحاً عالية أو حرجة.`, { metric: { label: 'High or critical open', value: n(k.highOpen), target: 0 }, link: '/incidents?status=OPEN', action: { tool: 'incidents.list', args: { status: 'OPEN', severity: 'HIGH', limit: 10 }, label: 'List the high-severity cases', labelAr: 'اعرض الحالات عالية الخطورة', tier: 'READ' } }));
      if (n(data?.injuryReportsOverdue) > 0) out.push(mk(module, 'injury-reports', 'warning', 'Injury reports are overdue', 'تقارير إصابات متأخرة', `${n(data.injuryReportsOverdue)} injury report(s) are past the statutory filing window.`, `${n(data.injuryReportsOverdue)} تقرير إصابة تجاوز مهلة الإبلاغ.`, { link: '/incidents' }));
      if (n(k.mttaMin) > 30) out.push(mk(module, 'mtta', 'info', 'Acknowledgement is slow', 'الاستجابة الأولية بطيئة', `Incidents take ${n(k.mttaMin)} minutes on average to be acknowledged; the desk's own target is 30.`, `يستغرق الإقرار بالحوادث ${n(k.mttaMin)} دقيقة في المتوسط مقابل هدف 30.`, { metric: { label: 'MTTA', value: n(k.mttaMin), target: 30 }, link: '/incidents/overview' }));
      break;
    }
    case 'inspect': {
      if (n(k.detentionRatePct) > 5) out.push(mk(module, 'detentions', 'warning', 'The detention rate is above the regional norm', 'معدل الاحتجاز أعلى من المعدل الإقليمي', `Detentions run at ${n(k.detentionRatePct).toFixed(1)}% of inspections; the Riyadh MoU regional figure is nearer 5%.`, `تبلغ الاحتجازات ${n(k.detentionRatePct).toFixed(1)}% من عمليات التفتيش مقابل نحو 5% إقليمياً.`, { metric: { label: 'Detention rate', value: n(k.detentionRatePct), target: 5, format: 'pct' }, link: '/inspections/detentions', action: { tool: 'inspect.detentions', args: { limit: 10 }, label: 'Show the detentions', labelAr: 'اعرض الاحتجازات', tier: 'READ' } }));
      if (n(k.openFindings) > 0) out.push(mk(module, 'findings', n(k.openFindings) > 100 ? 'warning' : 'info', 'Deficiencies are outstanding', 'أوجه قصور معلقة', `${n(k.openFindings)} deficiencies are open across ${n(k.open)} open inspection(s), ${n(k.avgFindings).toFixed(1)} per inspection on average.`, `${n(k.openFindings)} من أوجه القصور مفتوحة عبر ${n(k.open)} تفتيشاً مفتوحاً.`, { metric: { label: 'Open deficiencies', value: n(k.openFindings) }, link: '/inspections/deficiencies' }));
      if (n(k.checklistCompliancePct, 100) < 90) out.push(mk(module, 'checklists', 'info', 'Checklists are not being completed', 'قوائم التحقق لا تُستكمل', `Only ${pct(k.checklistCompliancePct)} of inspections completed their checklist in full.`, `${pct(k.checklistCompliancePct)} فقط من عمليات التفتيش أكملت قائمة التحقق.`, { metric: { label: 'Checklist compliance', value: n(k.checklistCompliancePct), target: 90, format: 'pct' }, link: '/inspections' }));
      break;
    }
    case 'facil': {
      const exp: Row = data?.expiries ?? {}; const obl: Row = data?.obligations ?? {};
      if (n(k.expired) + n(exp.expired) > 0) out.push(mk(module, 'expired', 'critical', 'Licences have expired', 'تراخيص منتهية', `${n(k.expired) || n(exp.expired)} licence(s) held by companies have expired; a company trading on one is unlicensed.`, `${n(k.expired) || n(exp.expired)} ترخيصاً منتهياً لدى الشركات.`, { metric: { label: 'Expired', value: n(k.expired) || n(exp.expired), target: 0 }, link: '/companies/licences' }));
      if (n(k.dueForRenewal) > 0) out.push(mk(module, 'renewals', 'warning', 'Licences are due for renewal', 'تراخيص مستحقة التجديد', `${n(k.dueForRenewal)} licence(s) fall due within the renewal window; ${n(exp.d30)} within 30 days.`, `${n(k.dueForRenewal)} ترخيصاً يستحق التجديد؛ ${n(exp.d30)} خلال 30 يوماً.`, { metric: { label: 'Due for renewal', value: n(k.dueForRenewal) }, link: '/companies/overview', action: { tool: 'facil.renewals', args: {}, label: 'List the renewals due', labelAr: 'اعرض التجديدات المستحقة', tier: 'READ' } }));
      if (n(obl.overdue) > 0) out.push(mk(module, 'obligations', 'warning', 'Obligations are overdue', 'التزامات متأخرة', `${n(obl.overdue)} of ${n(obl.open ?? k.openObligations)} open obligation(s) are past their date.`, `${n(obl.overdue)} من ${n(obl.open ?? k.openObligations)} التزاماً مفتوحاً تجاوز موعده.`, { metric: { label: 'Overdue obligations', value: n(obl.overdue), target: 0 }, link: '/companies/obligations' }));
      if (n(k.suspended) > 0) out.push(mk(module, 'suspended', 'info', 'Companies are suspended', 'شركات موقوفة', `${n(k.suspended)} company(ies) are suspended; a suspension that outlives its reason blocks lawful trade.`, `${n(k.suspended)} شركة موقوفة.`, { link: '/companies?status=SUSPENDED' }));
      break;
    }
    case 'services': {
      const desk: Row = data?.desk ?? {}; const ageing: Row[] = Array.isArray(data?.ageing) ? data.ageing : [];
      const old = ageing.filter((a) => /60|31/.test(String(a.label ?? a.bucket ?? ''))).reduce((s, a) => s + n(a.value ?? a.count), 0);
      if (n(data?.breached) > 0) out.push(mk(module, 'breached', 'critical', 'Applications are past their service level', 'طلبات تجاوزت مستوى الخدمة', `${n(data.breached)} open application(s) are past the service level the catalogue promises${n(desk.atRisk48h) ? `, and ${n(desk.atRisk48h)} more breach within 48 h` : ''}.`, `${n(data.breached)} طلباً مفتوحاً تجاوز مستوى الخدمة.`, { metric: { label: 'Breached', value: n(data.breached), target: 0 }, link: '/services/requests?scope=breached', action: { tool: 'services.applications', args: { scope: 'breached', limit: 20 }, label: 'List the breached applications', labelAr: 'اعرض الطلبات المتجاوزة', tier: 'READ' } }));
      if (n(desk.withinSlaPct90d, 100) < n(t.withinSlaPct, 90)) out.push(mk(module, 'sla', 'warning', 'Decisions within the service level are below target', 'القرارات ضمن مستوى الخدمة دون الهدف', `${pct(desk.withinSlaPct90d)} of decisions in 90 days were within the service level against a target of ${pct(t.withinSlaPct ?? 90)}; median time to decide ${n(desk.medianDecisionDays90d).toFixed(1)} days.`, `${pct(desk.withinSlaPct90d)} من القرارات خلال 90 يوماً كانت ضمن مستوى الخدمة مقابل هدف ${pct(t.withinSlaPct ?? 90)}.`, { metric: { label: 'Within SLA', value: n(desk.withinSlaPct90d), target: n(t.withinSlaPct, 90), format: 'pct' }, link: '/services/overview' }));
      if (old > 0) out.push(mk(module, 'ageing', 'warning', 'Applications are ageing', 'طلبات متقادمة', `${old} open application(s) are older than 30 days; the oldest has waited ${n(desk.oldestOpenDays)} days.`, `${old} طلباً مفتوحاً أقدم من 30 يوماً؛ أقدمها انتظر ${n(desk.oldestOpenDays)} يوماً.`, { metric: { label: 'Older than 30 days', value: old }, link: '/services/requests?scope=open' }));
      if (n(desk.feesOutstanding) > 0) out.push(mk(module, 'fees', 'info', 'Fees are outstanding on applications', 'رسوم معلقة على الطلبات', `${money(desk.feesOutstanding)} in fees are outstanding on ${n(desk.feesDueCount)} application(s); they do not move until paid.`, `${money(desk.feesOutstanding)} رسوماً معلقة على ${n(desk.feesDueCount)} طلباً.`, { metric: { label: 'Fees outstanding', value: n(desk.feesOutstanding), format: 'money' }, link: '/services/requests' }));
      break;
    }
    case 'finance': {
      const cur = data?.currency ?? 'AED'; const overdue: Row[] = Array.isArray(data?.overdueList) ? data.overdueList : [];
      if (n(k.overdueCount) > 0) out.push(mk(module, 'overdue', 'critical', 'Invoices are overdue', 'فواتير متأخرة', `${money(k.overdueAmount, cur)} is overdue on ${n(k.overdueCount)} invoice(s); ${n(k.remindersDue)} have had no reminder yet.`, `${money(k.overdueAmount, cur)} متأخرة على ${n(k.overdueCount)} فاتورة؛ ${n(k.remindersDue)} لم يُرسل لها تذكير بعد.`, { metric: { label: 'Overdue', value: n(k.overdueAmount), format: 'money' }, link: '/invoices?overdue=true', action: { tool: 'finance.invoices', args: { overdue: 'true', limit: 20 }, label: 'List the overdue invoices', labelAr: 'اعرض الفواتير المتأخرة', tier: 'READ' } }));
      for (const inv of overdue.filter((i) => !i.remindedAt).slice(0, 3)) {
        out.push(mk(module, `remind-${inv.id}`, 'warning', `Remind ${inv.billTo ?? inv.party ?? 'the debtor'} about ${inv.number}`, `تذكير ${inv.billTo ?? 'المدين'} بالفاتورة ${inv.number}`, `${inv.number} for ${money(inv.balance ?? inv.total, cur)} has been overdue ${n(inv.daysOverdue)} day(s) and no reminder has been sent.`, `الفاتورة ${inv.number} بمبلغ ${money(inv.balance ?? inv.total, cur)} متأخرة ${n(inv.daysOverdue)} يوماً ولم يُرسل تذكير.`, { metric: { label: 'Days overdue', value: n(inv.daysOverdue), format: 'days' }, link: `/invoices/${inv.id}`, action: { tool: 'finance.send_reminder', args: { id: inv.id }, label: 'Send the reminder', labelAr: 'أرسل التذكير', tier: 'ACT' } }));
      }
      if (n(k.dsoDays) > n(t.dsoDays, 40)) out.push(mk(module, 'dso', 'warning', 'Days sales outstanding is above the terms', 'أيام المبيعات المستحقة أعلى من الشروط', `DSO is ${n(k.dsoDays).toFixed(1)} days against ${n(t.dsoDays, 40)} (terms plus ten); cash arrives slower than the tariff assumes.`, `أيام المبيعات المستحقة ${n(k.dsoDays).toFixed(1)} يوماً مقابل ${n(t.dsoDays, 40)}.`, { metric: { label: 'DSO', value: n(k.dsoDays), target: n(t.dsoDays, 40), format: 'days' }, link: '/invoices/overview' }));
      if (n(k.ceiPct, 100) < n(t.ceiPct, 90)) out.push(mk(module, 'cei', 'info', 'Collection effectiveness is below target', 'فعالية التحصيل دون الهدف', `CEI is ${pct(k.ceiPct)} against ${pct(t.ceiPct ?? 90)}.`, `مؤشر فعالية التحصيل ${pct(k.ceiPct)} مقابل ${pct(t.ceiPct ?? 90)}.`, { metric: { label: 'CEI', value: n(k.ceiPct), target: n(t.ceiPct, 90), format: 'pct' }, link: '/invoices/overview' }));
      if (n(k.drafts?.count) > 0) out.push(mk(module, 'drafts', 'info', 'Draft invoices await issue', 'مسودات فواتير بانتظار الإصدار', `${n(k.drafts.count)} draft(s) worth ${money(k.drafts.total, cur)} are not yet issued, so nothing is due on them.`, `${n(k.drafts.count)} مسودة بقيمة ${money(k.drafts.total, cur)} لم تُصدر بعد.`, { metric: { label: 'Drafts', value: n(k.drafts.total), format: 'money' }, link: '/invoices?status=DRAFT' }));
      break;
    }
    case 'mis': {
      if (n(k.certsExpired) > 0) out.push(mk(module, 'certs', 'warning', 'Expired certificates in the fleet', 'شهادات منتهية في الأسطول', `${n(k.certsExpired)} certificate(s) are expired and ${n(k.certsExpiring)} expiring.`, `${n(k.certsExpired)} شهادة منتهية و${n(k.certsExpiring)} تنتهي قريباً.`, { metric: { label: 'Expired', value: n(k.certsExpired), target: 0 }, link: '/vessels/certificates' }));
      if (n(k.openDeficiencies) > 50) out.push(mk(module, 'deficiencies', 'info', 'Deficiencies are piling up', 'أوجه القصور تتراكم', `${n(k.openDeficiencies)} deficiencies are open across the register.`, `${n(k.openDeficiencies)} من أوجه القصور مفتوحة.`, { metric: { label: 'Open deficiencies', value: n(k.openDeficiencies) }, link: '/inspections/deficiencies' }));
      if (n(k.atAnchorage) > n(k.vesselsAtBerth)) out.push(mk(module, 'anchorage', 'warning', 'More vessels at anchorage than alongside', 'سفن في المرسى أكثر من الراسية', `${n(k.atAnchorage)} vessel(s) are at anchorage against ${n(k.vesselsAtBerth)} alongside, with occupancy at ${pct(k.berthOccupancyPct)}.`, `${n(k.atAnchorage)} سفينة في المرسى مقابل ${n(k.vesselsAtBerth)} راسية.`, { link: '/ops/berth-plan' }));
      break;
    }
    case 'masters': {
      if (n(k.duplicates) > 0) out.push(mk(module, 'duplicates', 'warning', 'Duplicate master entries', 'مدخلات مكررة في البيانات الرئيسية', `${n(k.duplicates)} duplicate(s) sit in the masters; every downstream report counts them twice.`, `${n(k.duplicates)} مدخلاً مكرراً في البيانات الرئيسية.`, { metric: { label: 'Duplicates', value: n(k.duplicates), target: 0 }, link: '/masters/overview' }));
      if (n(k.invalid) > 0) out.push(mk(module, 'invalid', 'warning', 'Invalid master entries', 'مدخلات غير صالحة', `${n(k.invalid)} entries fail their own validation rules.`, `${n(k.invalid)} مدخلاً لا يجتاز قواعد التحقق.`, { metric: { label: 'Invalid', value: n(k.invalid), target: 0 }, link: '/masters/overview' }));
      if (n(k.arabicPct, 100) < 80) out.push(mk(module, 'bilingual', 'info', 'Arabic coverage is incomplete', 'التغطية العربية غير مكتملة', `${pct(k.arabicPct)} of master entries carry an Arabic label; the Arabic interface shows English where they do not.`, `${pct(k.arabicPct)} فقط من المدخلات تحمل تسمية عربية.`, { metric: { label: 'Arabic labels', value: n(k.arabicPct), target: 80, format: 'pct' }, link: '/masters' }));
      if (n(k.companyCompletenessPct, 100) < 90) out.push(mk(module, 'companies', 'info', 'Golden company records are incomplete', 'سجلات الشركات الذهبية غير مكتملة', `Company golden records are ${pct(k.companyCompletenessPct)} complete; contacts are the usual gap.`, `سجلات الشركات مكتملة بنسبة ${pct(k.companyCompletenessPct)}.`, { metric: { label: 'Company completeness', value: n(k.companyCompletenessPct), target: 90, format: 'pct' }, link: '/masters/companies' }));
      break;
    }
    case 'admin': {
      if (n(k.privilegedWithoutMfa) > 0) out.push(mk(module, 'privileged-mfa', 'critical', 'Privileged accounts without a second factor', 'حسابات مميزة بلا عامل ثانٍ', `${n(k.privilegedWithoutMfa)} of ${n(k.privileged)} privileged account(s) have not enrolled a second factor. These are the accounts an attacker wants most.`, `${n(k.privilegedWithoutMfa)} من ${n(k.privileged)} حساباً مميزاً لم يسجل عاملاً ثانياً.`, { metric: { label: 'Privileged without MFA', value: n(k.privilegedWithoutMfa), target: 0 }, link: '/admin/users?mfa=missing', action: { tool: 'admin.users', args: { mfa: 'missing', limit: 20 }, label: 'List the accounts', labelAr: 'اعرض الحسابات', tier: 'READ' } }));
      if (n(k.dormant) > 0) out.push(mk(module, 'dormant', 'warning', 'Dormant accounts', 'حسابات خاملة', `${n(k.dormant)} account(s) are dormant against the ${n(k.dormantDays, 90)}-day rule; the sweep deactivates them on its next run unless they are reviewed.`, `${n(k.dormant)} حساباً خاملاً مقابل قاعدة ${n(k.dormantDays, 90)} يوماً.`, { metric: { label: 'Dormant', value: n(k.dormant), target: 0 }, link: '/admin/users?dormant=true', action: { tool: 'admin.users', args: { dormant: 'true', limit: 20 }, label: 'List the dormant accounts', labelAr: 'اعرض الحسابات الخاملة', tier: 'READ' } }));
      if (n(k.changesPending) > 0) out.push(mk(module, 'approvals', 'info', 'Changes await a second person', 'تغييرات بانتظار شخص ثانٍ', `${n(k.changesPending)} privileged change(s) are waiting for a second approver.`, `${n(k.changesPending)} تغييراً مميزاً بانتظار موافقة ثانية.`, { link: '/admin/approvals', action: { tool: 'admin.changes', args: { status: 'PENDING' }, label: 'Show the queue', labelAr: 'اعرض قائمة الانتظار', tier: 'READ' } }));
      if (n(k.failedLogins24h) > 50) out.push(mk(module, 'failed-logins', 'warning', 'Many failed sign-ins in a day', 'محاولات دخول فاشلة كثيرة', `${n(k.failedLogins24h)} sign-in attempts failed in 24 hours; ${n(k.lockedAccounts)} account(s) are locked.`, `${n(k.failedLogins24h)} محاولة دخول فاشلة خلال 24 ساعة؛ ${n(k.lockedAccounts)} حساباً مقفلاً.`, { metric: { label: 'Failed sign-ins, 24 h', value: n(k.failedLogins24h) }, link: '/admin/audit' }));
      if (n(k.mfaCoveragePct, 100) < 90) out.push(mk(module, 'mfa', 'info', 'Second-factor coverage is below target', 'تغطية العامل الثاني دون الهدف', `${pct(k.mfaCoveragePct)} of accounts that must hold a second factor have enrolled one; ${n(k.mfaOverdue)} are past their grace period.`, `${pct(k.mfaCoveragePct)} من الحسابات المطلوب منها عامل ثانٍ سجلته.`, { metric: { label: 'MFA coverage', value: n(k.mfaCoveragePct), target: 90, format: 'pct' }, link: '/admin/overview' }));
      break;
    }
    case 'platform': {
      const s: Row = data?.summary ?? {};
      if (n(s.servicesUp) < n(s.services)) out.push(mk(module, 'down', 'critical', 'Services are down', 'خدمات متوقفة', `${n(s.services) - n(s.servicesUp)} of ${n(s.services)} services are not answering.`, `${n(s.services) - n(s.servicesUp)} من ${n(s.services)} خدمة لا تستجيب.`, { metric: { label: 'Services up', value: `${n(s.servicesUp)}/${n(s.services)}` }, link: '/platform' }));
      if (n(s.openIncidents) > 0) out.push(mk(module, 'incidents', 'warning', 'Platform incidents are open', 'حوادث منصة مفتوحة', `${n(s.openIncidents)} platform incident(s) are open.`, `${n(s.openIncidents)} حادث منصة مفتوح.`, { link: '/platform/incidents' }));
      break;
    }
    default: break;
  }
  const rank: Record<Severity, number> = { critical: 0, warning: 1, info: 2 };
  return out.sort((a, b) => rank[a.severity] - rank[b.severity]).map((i) => ({ ...i, generatedAt: now.toISOString() } as Insight));
}
