import { join } from 'node:path';
import { buildWorld, isStatutory, type World } from '@maritime/world';
import { makeEvent, EVENTS } from '@maritime/contracts';
import { createDb, runMigrations, withTx } from '@maritime/service-kit';
import { env } from './env';
import { project } from './consumer';

/** Report library — saved reports run over the read models. Bilingual names; categories match the module colours. */
export const REPORTS = [
  { key: 'port-calls-by-month', name: 'Port calls by month', nameAr: 'المكالمات الميناء حسب الشهر', category: 'Traffic', description: 'Calls, sailings, turnaround and cargo per month', perm: 'portcalls.view', params: [{ name: 'months', label: 'Months', type: 'number', default: 12 }], columns: [{ key: 'month', label: 'Month' }, { key: 'calls', label: 'Calls', align: 'right' }, { key: 'sailed', label: 'Sailed', align: 'right' }, { key: 'avg_turnaround_h', label: 'Avg turnaround (h)', align: 'right' }, { key: 'cargo_mt', label: 'Cargo (MT)', align: 'right' }, { key: 'teu', label: 'TEU', align: 'right' }], queryKey: 'portCallsByMonth' },
  { key: 'cargo-by-commodity', name: 'Cargo by commodity', nameAr: 'البضائع حسب السلعة', category: 'Traffic', description: 'Tonnage and operations per commodity', perm: 'portcalls.view', params: [{ name: 'months', label: 'Months', type: 'number', default: 12 }], columns: [{ key: 'commodity', label: 'Commodity' }, { key: 'cargo_mt', label: 'Cargo (MT)', align: 'right' }, { key: 'operations', label: 'Operations', align: 'right' }], queryKey: 'cargoByCommodity' },
  { key: 'berth-occupancy', name: 'Berth occupancy', nameAr: 'إشغال الأرصفة', category: 'Traffic', description: 'Hours alongside and occupancy per berth, trailing 12 months', perm: 'portcalls.view', params: [], columns: [{ key: 'code', label: 'Berth' }, { key: 'terminal', label: 'Terminal' }, { key: 'berth_type', label: 'Type' }, { key: 'calls_12m', label: 'Calls', align: 'right' }, { key: 'hours_alongside', label: 'Hours alongside', align: 'right' }, { key: 'occupancy_pct', label: 'Occupancy %', align: 'right' }], queryKey: 'berthOccupancy' },
  { key: 'vessel-calls', name: 'Vessel call frequency', nameAr: 'تكرار مكالمات السفن', category: 'Fleet', description: 'Calls per vessel in the window', perm: 'vessels.view', params: [{ name: 'months', label: 'Months', type: 'number', default: 12 }], columns: [{ key: 'name', label: 'Vessel' }, { key: 'imo', label: 'IMO' }, { key: 'type', label: 'Type' }, { key: 'flag', label: 'Flag' }, { key: 'calls', label: 'Calls', align: 'right' }, { key: 'last_call', label: 'Last call' }], queryKey: 'vesselCalls' },
  { key: 'agent-performance', name: 'Agent performance', nameAr: 'أداء الوكلاء', category: 'Traffic', description: 'Calls, waiting and turnaround by shipping agent', perm: 'portcalls.view', params: [{ name: 'months', label: 'Months', type: 'number', default: 12 }], columns: [{ key: 'agent_code', label: 'Code' }, { key: 'agent_name', label: 'Agent' }, { key: 'calls', label: 'Calls', align: 'right' }, { key: 'avg_wait_h', label: 'Avg wait (h)', align: 'right' }, { key: 'avg_turnaround_h', label: 'Avg turnaround (h)', align: 'right' }], queryKey: 'agentPerformance' },
  { key: 'revenue-by-month', name: 'Revenue by month', nameAr: 'الإيرادات حسب الشهر', category: 'Revenue', description: 'Billed, tax and collected per month', perm: 'invoices.view', params: [{ name: 'months', label: 'Months', type: 'number', default: 12 }], columns: [{ key: 'month', label: 'Month' }, { key: 'invoices', label: 'Invoices', align: 'right' }, { key: 'subtotal', label: 'Subtotal', align: 'right' }, { key: 'tax', label: 'Tax', align: 'right' }, { key: 'total', label: 'Total', align: 'right' }, { key: 'collected', label: 'Collected', align: 'right' }], queryKey: 'revenueByMonth' },
  { key: 'outstanding-invoices', name: 'Outstanding invoices', nameAr: 'الفواتير المستحقة', category: 'Revenue', description: 'Issued and unpaid, oldest first', perm: 'invoices.view', params: [], columns: [{ key: 'number', label: 'Invoice' }, { key: 'vessel_name', label: 'Vessel' }, { key: 'bill_to_name', label: 'Bill to' }, { key: 'total', label: 'Total', align: 'right' }, { key: 'issued_at', label: 'Issued' }, { key: 'days_outstanding', label: 'Days', align: 'right' }], queryKey: 'outstandingInvoices' },
  { key: 'inspection-summary', name: 'Inspection summary', nameAr: 'ملخص التفتيش', category: 'Compliance', description: 'Inspections, detentions and findings by type', perm: 'inspections.view', params: [{ name: 'months', label: 'Months', type: 'number', default: 12 }], columns: [{ key: 'type', label: 'Type' }, { key: 'inspections', label: 'Inspections', align: 'right' }, { key: 'closed', label: 'Closed', align: 'right' }, { key: 'detentions', label: 'Detentions', align: 'right' }, { key: 'findings', label: 'Findings', align: 'right' }, { key: 'open_findings', label: 'Open', align: 'right' }, { key: 'avg_score', label: 'Avg score %', align: 'right' }], queryKey: 'inspectionSummary' },
  { key: 'detentions', name: 'Detention register', nameAr: 'سجل الاحتجاز', category: 'Compliance', description: 'Detentions ordered in the window', perm: 'inspections.view', params: [{ name: 'months', label: 'Months', type: 'number', default: 12 }], columns: [{ key: 'number', label: 'Inspection' }, { key: 'vessel_name', label: 'Vessel' }, { key: 'type', label: 'Type' }, { key: 'inspector', label: 'Inspector' }, { key: 'closed_at', label: 'Closed' }, { key: 'total_findings', label: 'Findings', align: 'right' }], queryKey: 'detentions' },
  { key: 'certificate-expiry', name: 'Certificate expiry', nameAr: 'انتهاء الشهادات', category: 'Fleet', description: 'Fleet certificates expiring within the window', perm: 'certificates.view', params: [{ name: 'days', label: 'Days ahead', type: 'number', default: 90 }], columns: [{ key: 'vessel', label: 'Vessel' }, { key: 'imo', label: 'IMO' }, { key: 'cert_type', label: 'Certificate' }, { key: 'number', label: 'Number' }, { key: 'issuer', label: 'Issuer' }, { key: 'expiry_date', label: 'Expires' }], queryKey: 'certificateExpiry' },
  { key: 'incident-summary', name: 'Incident summary', nameAr: 'ملخص الحوادث', category: 'Safety', description: 'Cases by category, type and severity', perm: 'incidents.view', params: [{ name: 'months', label: 'Months', type: 'number', default: 12 }], columns: [{ key: 'category', label: 'Category' }, { key: 'type', label: 'Type' }, { key: 'severity', label: 'Severity' }, { key: 'cases', label: 'Cases', align: 'right' }, { key: 'closed', label: 'Closed', align: 'right' }, { key: 'avg_close_days', label: 'Avg close (d)', align: 'right' }], queryKey: 'incidentSummary' },
  { key: 'crew-roster', name: 'Crew roster', nameAr: 'قائمة الطاقم', category: 'Crew', description: 'Every seafarer on the roll with assignment and alerts', perm: 'seafarers.view', params: [], columns: [{ key: 'name', label: 'Name' }, { key: 'rank', label: 'Rank' }, { key: 'cdc_no', label: 'CDC' }, { key: 'nationality', label: 'Nationality' }, { key: 'status', label: 'Status' }, { key: 'current_vessel_name', label: 'On board' }, { key: 'cert_alerts', label: 'Alerts', align: 'right' }], queryKey: 'crewRoster' },
  { key: 'licence-register', name: 'Licence register', nameAr: 'سجل التراخيص', category: 'Companies', description: 'Company and facility licences by expiry', perm: 'facilities.view', params: [], columns: [{ key: 'number', label: 'Number' }, { key: 'entity_name', label: 'Holder' }, { key: 'entity_type', label: 'Type' }, { key: 'status', label: 'Status' }, { key: 'issue_date', label: 'Issued' }, { key: 'expiry_date', label: 'Expires' }, { key: 'performance_rating', label: 'Rating', align: 'right' }], queryKey: 'licenceRegister' },
  { key: 'notices-register', name: 'Notices & circulars register', nameAr: 'سجل الإشعارات والتعاميم', category: 'Compliance', description: 'Every instrument with acknowledgment counts', perm: 'legislation.view', params: [], columns: [{ key: 'ref_no', label: 'Ref' }, { key: 'title', label: 'Title' }, { key: 'type', label: 'Type' }, { key: 'status', label: 'Status' }, { key: 'issued_date', label: 'Issued' }, { key: 'acknowledgments', label: 'Acknowledged', align: 'right' }], queryKey: 'noticesRegister' },
  { key: 'user-activity', name: 'User activity', nameAr: 'نشاط المستخدمين', category: 'Administration', description: 'Accounts by last sign-in', perm: 'users.view', params: [], columns: [{ key: 'name', label: 'Name' }, { key: 'email', label: 'Email' }, { key: 'role_name', label: 'Role' }, { key: 'department', label: 'Department' }, { key: 'active', label: 'Active' }, { key: 'last_login_at', label: 'Last sign-in' }], queryKey: 'userActivity' },
  { key: 'audit-summary', name: 'Audit summary', nameAr: 'ملخص التدقيق', category: 'Administration', description: 'Entries by entity and action', perm: 'audit.view', params: [{ name: 'days', label: 'Days', type: 'number', default: 30 }], columns: [{ key: 'entity', label: 'Entity' }, { key: 'action', label: 'Action' }, { key: 'entries', label: 'Entries', align: 'right' }, { key: 'last_at', label: 'Last' }], queryKey: 'auditSummary' },
  { key: 'tariff-schedule', name: 'Tariff schedule', nameAr: 'جدول التعرفة', category: 'Revenue', description: 'The published rate card', perm: 'tariffs.view', params: [], columns: [{ key: 'code', label: 'Code' }, { key: 'name', label: 'Charge' }, { key: 'category', label: 'Category' }, { key: 'unit', label: 'Unit' }, { key: 'rate', label: 'Rate', align: 'right' }, { key: 'active', label: 'Active' }, { key: 'revisions', label: 'Revisions', align: 'right' }], queryKey: 'tariffSchedule' },
];

const ev = (kind: string, entity: unknown) => makeEvent({ type: EVENTS.readModel.upserted, source: 'seed', data: { kind, entity } });
const pick = <T>(w: World, key: string): T[] => ((w as unknown as Record<string, unknown>)[key] as T[] | undefined) ?? [];

/** Seeds the read models from the shared world through the same projections the event consumer uses, so seed and live paths cannot drift. */
export async function seedReporting(databaseUrl: string, profile?: string) {
  const { pool } = createDb(databaseUrl);
  await runMigrations(pool, join(__dirname, '..', 'migrations'));
  const world = buildWorld({ profile });
  const byId = new Map(world.vessels.map((v) => [v.id, v])); const berthByCode = new Map(world.berths.map((b) => [b.code, b])); const companyByCode = new Map(world.companies.map((c) => [c.code, c]));
  const counts: Record<string, number> = {};
  await withTx(pool, async (c) => {
    const run = async (kind: string, rows: unknown[]) => { for (const r of rows) await project(c, ev(kind, r)); counts[kind] = rows.length; };
    await run('user', world.users.map((u) => ({ ...u, role: { name: u.roleName } })));
    await run('berth', world.berths.map((b) => ({ ...b, outages: pick<{ berthId: string }>(world, 'berthOutages').filter((o) => o.berthId === b.id) })));
    await run('company', world.companies);
    await run('vessel', world.vessels.map((v) => ({ ...v, agentName: companyByCode.get(v.agentCode)?.name ?? null, registry: pick<{ vesselId: string }>(world, 'registry').find((r) => r.vesselId === v.id) ?? {} })));
    await run('instrument', pick<{ entityType: string; status: string; endorsements?: { result: string }[] }>(world, 'licences').map((l) => ({ ...l, statutory: isStatutory(l.entityType), inForce: !(l.endorsements ?? []).some((x) => x.result === 'NOT_ENDORSED'), signed: l.status === 'ISSUED' })));
    await run('portCall', world.portCalls.map((p) => ({ ...p, vesselType: byId.get(p.vesselId)?.type ?? null, agentName: companyByCode.get(p.agentCode)?.name ?? null, berthId: p.berthCode ? berthByCode.get(p.berthCode)?.id ?? null : null })));
    for (const [kind, key] of [['vesselCertificate', 'vesselCertificates'], ['invoice', 'invoices'], ['inspection', 'inspections'], ['incident', 'incidents'], ['seafarer', 'seafarers'], ['legalInstrument', 'legalInstruments'], ['registration', 'registrations'], ['tariff', 'tariffs'], ['resource', 'resources'], ['checklistTemplate', 'checklistTemplates'], ['agentDecision', 'aiDecisions']] as const) await run(kind, pick(world, key));
    const cats = new Map<string, number>(); for (const l of world.lookups) cats.set(l.category, (cats.get(l.category) ?? 0) + 1);
    for (const [category, entries] of cats) await c.query('INSERT INTO rm_lookup_counts(category, entries) VALUES ($1, $2) ON CONFLICT (category) DO UPDATE SET entries = EXCLUDED.entries', [category, entries]);
    for (const r of REPORTS) await c.query('INSERT INTO report_definitions(key, name, name_ar, category, description, perm, params, columns, query_key) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT (key) DO UPDATE SET name = EXCLUDED.name, name_ar = EXCLUDED.name_ar, category = EXCLUDED.category, description = EXCLUDED.description, perm = EXCLUDED.perm, params = EXCLUDED.params, columns = EXCLUDED.columns, query_key = EXCLUDED.query_key', [r.key, r.name, r.nameAr, r.category, r.description, r.perm, JSON.stringify(r.params), JSON.stringify(r.columns), r.queryKey]);
    counts.reports = REPORTS.length;
  });
  await pool.end();
  return { ...counts, profile: world.profile };
}
if (require.main === module) {
  const e = env();
  seedReporting(e.DATABASE_URL).then((c) => console.log('SEED COMPLETE', c)).catch((err) => { console.error(err); process.exit(1); });
}
